# inspect_code — inspection multi-source d'un code CIM-10

Version notebook de `scripts/explore/2026-05-28_inspect_code.py`. **Ne pas éditer directement** — modifier le `.py` et re-convertir.

In [2]:
from __future__ import annotations

from recode_icd.utils.loaders_dev import inspect_code, load_exploration_context

# Charge le contexte AVEC les sources externes brutes (nécessaire au
# BLOC 2). Coût ~5 s (parse XML ORPHANET + xlsx HECTOR). Réutilisable
# pour tous les appels inspect_code(..., ctx=ctx) ci-dessous.
ctx = load_exploration_context(with_external=True)

 inspect_code — mode d'emploi

`inspect_code(codes, ctx=None)` affiche un rapport texte en 4 blocs
pour un ou plusieurs codes CIM-10 :

- **BLOC 1 — Identité** : libellés OFS/ANS, position hiérarchique
  (chapitre / bloc / catégorie), type.
- **BLOC 2 — Sources brutes** : ce que dit chaque source avant fusion
  (OFS, ANS, ORPHANET avec relation E/NTBT, Index CIM-10 vol3, AP-HP
  par spécialité).
- **BLOC 3 — Dague/astérisque** : les associations de la table DAGSTAR
  enrichie (partenaire, redundancy_level, niveaux présents).
- **BLOC 4 — Résultat final** : les lignes du CSV maître pour ce code,
  réparties par (type, source), avec source_level / inherited_from_code.

**Résolution des codes** :
- `"A18.1"` → le code exact (s'il existe dans le CSV).
- `"A18"` → préfixe : tous les codes du CSV commençant par `A18`.
- `["A18.1", "N33.0"]` → liste de codes/préfixes.

`ctx=None` recharge automatiquement le contexte avec les sources
externes. Ici on passe `ctx=ctx` pour réutiliser le contexte déjà
chargé (plus rapide).

In [3]:
inspect_code("A18.1", ctx=ctx)

╔════════════════════════════════════════════════════════════════════╗
║ A18.1 — Tuberculose de l'appareil génito-urinaire                  ║
╚════════════════════════════════════════════════════════════════════╝

── BLOC 1 : IDENTITÉ ─────────────────────────────────────────────────
Code         : A18.1
Libellé OFS  : tuberculose de l'appareil génito-urinaire
Libellé ANS  : Tuberculose de l'appareil génito-urinaire
Type         : category
Chapitre     : I — Certaines maladies infectieuses et parasitaires
Bloc         : A15-A19 — Tuberculose
Catégorie    : A18 — Tuberculose d'autres organes

── BLOC 2 : SOURCES BRUTES (avant fusion) ────────────────────────────
[OFS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Descripteurs / synonymes :
    - tuberculose (de) uretère
    - tuberculose (de) vessie
    - tuberculose (de) organes génitaux de l'homme
    - tuberculose (de) col de l'utérus
    - tuberculose (de) rénale
    - affection inflammatoire tuberculeuse des organes pelviens de la femme
  Notes éditoriales :
    (aucune entrée)

[ANS]
  Inclusions :
    - Affection inflammatoire tuberculeuse des organes pelviens de la femme [N74.1]
Tuberculose (de) :
 - col de l'utérus [N74.0]
 - organes génitaux de l'homme [N51.-]
 - rénale [N29.1]
 - uretère [N29.1]
 - vessie [N33.0]

  Exclusions :
    (aucune entrée)
  Synonymes :
    - Affection inflammatoire tuberculeuse des organes pelviens de la femme
    - Tuberculose (de) col de l'utérus
    - Tuberculose (de) vessie
    - Tuberculose (de) uretère
    - Tuberculose (de) rénale
    - Tuberculose (de) organes génitaux de l'homme
  Notes (définitions / scope) :
    (aucune entrée)

[SOURCES EXTERNES]
  ORPHANET (2) :
    - Tuberculose génito-urinaire primaire  [synonyme, E]
    - Tuberculose urogénitale  [synonyme, E]
  INDEX_CIM10_VOL3 (91) :
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), glande(s) (de), bulbo-urétrale(s), tuberculeux  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), glande(s) (de), cowper, tuberculeux  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), pelvien, femme, tuberculeux  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), périnéphrétique, tuberculeux  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, glande de cowper  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, génito-urinaire (femme)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, pelvien (femme)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, périnéphrétique  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, rein  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, scrotum  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, testicule  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, utérus  [synonyme]
    - Adhérences (post-infectieuses) (de), pelviennes, pelvi-péritonéales (homme) (voir aussi adhérences, péritonéales), tuberculeuses  [synonyme]
    - Bacillurie (voir aussi bactériurie), tuberculeuse  [synonyme]
    - Cervicite (aiguë) (avec ectropion ou érosion du col) (chronique) (non sexuellement transmissible) (subaiguë) (à), tuberculeuse  [synonyme]
    - Cystite (exsudative) (hémorragique) (purulente) (suppurée) (à), tuberculeuse  [synonyme]
    - Déférentite (à), tuberculeuse  [synonyme]
    - Endométrite (infectieuse) (non spécifique) (purulente) (suppurée) (à), tuberculeuse  [synonyme]
    - Epididymite (aiguë) (non sexuellement transmissible) (récidivante) (résiduelle) (due à), tuberculeuse  [synonyme]
    - Fistule (de), scrotum (urinaire), tuberculeuse  [synonyme]
    - Fistule (de), urètre, tuberculeuse  [synonyme]
    - Fistule (de), épididyme, tuberculeuse  [synonyme]
    - Funiculite (aiguë) (chronique) (endémique) (à), tuberculeuse  [synonyme]
    - Glomérulonéphrite (à), au cours de (voir aussi glomérulopathie, au cours de), tuberculose  [synonyme]
    - Hydronéphrose (atrophique) (intermittente) (primitive) (secondaire), tuberculeuse  [synonyme]
    - Hématurie (essentielle), tuberculeuse  [synonyme]
    - Infection (à) (de), urinaire (voies), tuberculeuse  [synonyme]
    - Kyste (colloïde) (muqueux) (séreux) (de), ovaire, ovarien (adhérent) (d'involution) (hémorragique) (rétentionnel) (séreux) (tordu) nca, tuberculeux  [synonyme]
    - Maladie (à) (de) rein (bassinet) (fonctionnelle), au cours de, tuberculose  [synonyme]
    - Métrite (infectieuse) (purulente) (à) (voir aussi endométrite), tuberculeuse  [synonyme]
    - Néphrite (à) (voir aussi syndrome, néphritique), au cours de, tuberculose  [synonyme]
    - Néphrite (à) (voir aussi syndrome, néphritique), tuberculeuse  [synonyme]
    - Néphrite (à) (voir aussi syndrome, néphritique), tubulo-interstitielle (voir aussi trouble, tubulo- interstitiel), tuberculeuse  [synonyme]
    - Néphropathie, au cours de (voir aussi glomérulopathie, au cours de), tuberculose  [synonyme]
    - Orchite (aiguë) (gangréneuse) (infectée) (suppurée) (à), tuberculeuse  [synonyme]
    - Ovarite (infectieuse) (interstitielle) (kystique) (à), tuberculeuse  [synonyme]
    - Prostatite (congestive) (suppurée) (à), tuberculeuse  [synonyme]
    - Pyélite (à) (voir aussi pyélonéphrite), tuberculeuse  [synonyme]
    - Pyélonéphrite (voir aussi pyélite), tuberculeuse  [synonyme]
    - Rétrécissement (de) - voir aussi sténose, trompe (de), fallope, tuberculeux  [synonyme]
    … (+51 de plus)
  APHP_NEPHROLOGIE (1) :
    - tuberculose génito-urinaire [coder d'abord 1141NL à 1144NL]  [synonyme]

── BLOC 3 : RELATIONS DAGUE/ASTÉRISQUE ───────────────────────────────
  • A18.1 est dague (†) ; apparié à N29.1 — autres affections du rein et de l'uretère au cours de maladies infectieuses et parasitaires classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A18.1 est dague (†) ; apparié à N33.0 — cystite tuberculeuse
      redundancy_level=subordinate ; levels_present=['G', 'U']
  • A18.1 est dague (†) ; apparié à N51 — affections des organes génitaux de l'homme au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['U']
  • A18.1 est dague (†) ; apparié à N51.0 — affections de la prostate au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['H']
  • A18.1 est dague (†) ; apparié à N51.1 — affections du testicule et de l'épididyme au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['H']
  • A18.1 est dague (†) ; apparié à N51.8 — autres affections des organes génitaux de l'homme au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['H']
  • A18.1 est dague (†) ; apparié à N74.0 — tuberculose du col de l'utérus
      redundancy_level=subordinate ; levels_present=['G', 'U']
  • A18.1 est dague (†) ; apparié à N74.1 — affection inflammatoire pelvienne tuberculeuse de la femme
      redundancy_level=independent ; levels_present=['G', 'U']
  • A18.1 est dague (†) ; apparié à N77.0 — ulcération de la vulve au cours de maladies infectieuses et parasitaires classées ailleurs
      redundancy_level=subordinate ; levels_present=['H']
  • A18.1 est dague (†) ; apparié à (aucun) —
      redundancy_level=none ; levels_present=['S']

── BLOC 4 : RÉSULTAT FINAL (CSV) ─────────────────────────────────────
  954 ligne(s). Répartition par (type, source) :
    synonyme   | CIM-10 index                 : 792
    synonyme   | CIM-10                       : 54
    exclusion  | CIM-10                       : 36
    exclusion  | ANS                          : 18
    inclusion  | ANS                          : 18
    synonyme   | ORPHANET                     : 18
    inclusion  | CIM-10                       : 9
    synonyme   | AP-HP Néphrologie            : 9

  Détail (type | source | source_level | inherited_from | texte) :
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | block    | A15-A19   | immunodéficience humaine virale [VIH] à l'origine
    exclusion | ANS                    | block    | A15-A19   | immunodéficience humaine virale [VIH] à l'origine
    exclusion | ANS                    | block    | A15-A19   | immunodéficience humaine virale [VIH] à l'origine
    exclusion | ANS                    | block    | A15-A19   | immunodéficience humaine virale [VIH] à l'origine
    … (+914 lignes de plus)

In [4]:
inspect_code("E84.8", ctx=ctx)

╔════════════════════════════════════════════════════════════════════╗
║ E84.8 — Fibrose kystique du pancréas avec autres manifestations    ║
╚════════════════════════════════════════════════════════════════════╝

── BLOC 1 : IDENTITÉ ─────────────────────────────────────────────────
Code         : E84.8
Libellé OFS  : fibrose kystique avec autres manifestations
Libellé ANS  : Fibrose kystique du pancréas avec autres manifestations
Type         : category
Chapitre     : IV — Maladies endocriniennes, nutritionnelles et métaboliques
Bloc         : E70-E90 — Anomalies du métabolisme
Catégorie    : E84 — Fibrose kystique du pancréas

── BLOC 2 : SOURCES BRUTES (avant fusion) ────────────────────────────
[OFS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Descripteurs / synonymes :
    - fibrose kystique avec manifestations associées
  Notes éditoriales :
    (aucune entrée)

[ANS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Synonymes :
    (aucune entrée)
  Notes (définitions / scope) :
    (aucune entrée)

[SOURCES EXTERNES]
  ORPHANET (2) :
    - Syndrome de Lubani-Al Saleh-Teebi  [inclusion, NTBT]
    - Syndrome de mucoviscidose-gastrite-anémie mégaloblastique  [inclusion, NTBT]
  INDEX_CIM10_VOL3 (4) :
    - Fibrose (de), kystique (du pancréas), avec manifestations, associées  [synonyme]
    - Fibrose (de), kystique (du pancréas), avec manifestations, précisées nca  [synonyme]
    - Ictère (de), nouveau-né (physiologique), associé à, dû à, mucoviscidose  [synonyme]
    - Maladie (à) (de) pancréas, fibrokystique  [synonyme]

── BLOC 3 : RELATIONS DAGUE/ASTÉRISQUE ───────────────────────────────
    (pas d'association dague/astérisque)

── BLOC 4 : RÉSULTAT FINAL (CSV) ─────────────────────────────────────
  18 ligne(s). Répartition par (type, source) :
    exclusion  | CIM-10                       : 6
    synonyme   | CIM-10 index                 : 4
    exclusion  | ANS                          : 2
    exclusion  | CIM-10 frères                : 2
    inclusion  | ORPHANET                     : 2
    inclusion  | CIM-10                       : 1
    synonyme   | CIM-10                       : 1

  Détail (type | source | source_level | inherited_from | texte) :
    inclusion | CIM-10                 | category | E84       | mucoviscidose
    inclusion | ORPHANET               | code     |           | Syndrome de Lubani-Al Saleh-Teebi
    inclusion | ORPHANET               | code     |           | Syndrome de mucoviscidose-gastrite-anémie mégalobl
    exclusion | ANS                    | chapter  | IV        | anomalies endocriniennes et métaboliques transitoi
    exclusion | ANS                    | block    | E70-E90   | anémies hémolytiques dues à des anomalies enzymati
    exclusion | CIM-10                 | block    | E70-E90   | anémies hémolytiques dues à des anomalies enzymati
    exclusion | CIM-10                 | block    | E70-E90   | déficit en 5-alpha-réductase
    exclusion | CIM-10                 | block    | E70-E90   | hyperplasie surrénale congénitale
    exclusion | CIM-10                 | block    | E70-E90   | syndrome de Ehlers-Danlos
    exclusion | CIM-10                 | block    | E70-E90   | syndrome de Marfan
    exclusion | CIM-10                 | block    | E70-E90   | syndrome de résistance aux androgènes
    exclusion | CIM-10 frères          | code     |           | Fibrose kystique du pancréas avec manifestations i
    exclusion | CIM-10 frères          | code     |           | Fibrose kystique du pancréas avec manifestations p
    synonyme  | CIM-10                 | code     |           | fibrose kystique avec manifestations associées
    synonyme  | CIM-10 index           | code     |           | Fibrose (de), kystique (du pancréas), avec manifes
    synonyme  | CIM-10 index           | code     |           | Fibrose (de), kystique (du pancréas), avec manifes
    synonyme  | CIM-10 index           | code     |           | Ictère (de), nouveau-né (physiologique), associé à
    synonyme  | CIM-10 index           | code     |           | Maladie (à) (de) pancréas, fibrokystique

In [5]:
inspect_code("A52.7", ctx=ctx)

╔════════════════════════════════════════════════════════════════════╗
║ A52.7 — Autres formes tardives de syphilis symptomatique           ║
╚════════════════════════════════════════════════════════════════════╝

── BLOC 1 : IDENTITÉ ─────────────────────────────────────────────────
Code         : A52.7
Libellé OFS  : autres formes tardives de syphilis symptomatique
Libellé ANS  : Autres formes tardives de syphilis symptomatique
Type         : category
Chapitre     : I — Certaines maladies infectieuses et parasitaires
Bloc         : A50-A64 — Infections dont le mode de transmission est essentiellement sexuel
Catégorie    : A52 — Syphilis tardive

── BLOC 2 : SOURCES BRUTES (avant fusion) ────────────────────────────
[OFS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Descripteurs / synonymes :
    - péritonite syphilitique tardive
    - syphilis tardive ou tertiaire toute localisation, sauf celles classées en A52.0, A52.1, A52.2, A52.3
    - syphilis [stade non précisé] pulmonaire
    - syphilis [stade non précisé] osseuse
    - syphilis [stade non précisé] musculaire
    - syphilis [stade non précisé] hépatique
    - épisclérite syphilitique tardive
    - synovite syphilitique [stade non précisé]
    - leucodermie syphilitique tardive
    - glomérulite syphilitique
    - gomme (syphilitique) toute localisation, sauf celles classées en A52.0, A52.1, A52.2, A52.3
    - choriorétinite syphilitique tardive
    - bursite syphilitique tardive
    - affection inflammatoire des organes pelviens de la femme syphilitique tardive
    - oculopathie NCA syphilitique tardive
  Notes éditoriales :
    (aucune entrée)

[ANS]
  Inclusions :
    - Affection inflammatoire des organes pelviens de la femme [N74.2]   syphilitique tardive
Bursite [M73.1]   syphilitique tardive
Choriorétinite [H32.0]   syphilitique tardive
Épisclérite [H19.0]   syphilitique tardive
Leucodermie [L99.8]   syphilitique tardive
Oculopathie NCA [H58.8]   syphilitique tardive
Péritonite [K67.2]   syphilitique tardive
Glomérulite syphilitique [N08.0]
Gomme (syphilitique)  toute localisation, sauf celles classées en A52.0-A52.3
Syphilis tardive ou tertiaire  toute localisation, sauf celles classées en A52.0-A52.3
Synovite syphilitique [stade non précisé] [M68.0]
Syphilis [stade non précisé] :
 - hépatique [K77.0]
 - musculaire [M63.0]
 - osseuse [M90.2]
 - pulmonaire [J99.8]

  Exclusions :
    (aucune entrée)
  Synonymes :
    - Syphilis [stade non précisé] musculaire
    - Épisclérite syphilitique tardive
    - Syphilis [stade non précisé] hépatique
    - Syphilis [stade non précisé] osseuse
    - Péritonite syphilitique tardive
    - Leucodermie syphilitique tardive
    - Synovite syphilitique [stade non précisé]
    - Bursite syphilitique tardive
    - Syphilis tardive ou tertiaire toute localisation, sauf celles classées en A52.0-A52.3
    - Oculopathie NCA syphilitique tardive
    - Choriorétinite syphilitique tardive
    - Syphilis [stade non précisé] pulmonaire
    - Glomérulite syphilitique
    - Gomme (syphilitique) toute localisation, sauf celles classées en A52.0-A52.3
    - Affection inflammatoire des organes pelviens de la femme syphilitique tardive
  Notes (définitions / scope) :
    (aucune entrée)

[SOURCES EXTERNES]
  INDEX_CIM10_VOL3 (151) :
    - Affection (à) (de) - voir aussi maladie, inflammatoire des organes pelviens chez la femme (à) (voir aussi maladie, pelvienne, inflammatoire), syphilitique (tardive)  [synonyme]
    - Affection (à) (de) - voir aussi maladie, organe(s) (voir aussi affection, selon l'organe), pelviens (femme), inflammatoire (à) (due à) (voir aussi maladie, pelvienne, inflammatoire), syphilitique (tardive)  [synonyme]
    - Affection (à) (de) - voir aussi maladie, poumon, pulmonaire nca, au cours de, syphilis (tardive)  [synonyme]
    - Arthropathie (à) (de) (voir aussi arthrite), syphilitique (tardive)  [synonyme]
    - Atrophie (de), cutanée (sénile), en stries, syphilitique (tardive)  [synonyme]
    - Atrophie (de), cutanée (sénile), en taches, et en stries, syphilitique (tardive)  [synonyme]
    - Atrophie (de), musculaire (d'), syphilitique (tardive)  [synonyme]
    - Babinski(-vaquez), syndrome de  [synonyme]
    - Bursite (de), syphilitique (tardive)  [synonyme]
    - Cervicite (aiguë) (avec ectropion ou érosion du col) (chronique) (non sexuellement transmissible) (subaiguë) (à), syphilitique (tardive)  [synonyme]
    - Choriorétinite, syphilitique (secondaire), tardive  [synonyme]
    - Cirrhose (cryptogénique) (macronodulaire) (micronodulaire) (portale) (post-nécrotique) (type mixte) (de), foie (chronique) (monolobulaire) (nodulaire) (plurilobulaire) (splénomégalique) (au cours de), syphilitique (tardive)  [synonyme]
    - Conjonctivite (de) (due à), syphilitique (secondaire) (tardive)  [synonyme]
    - Cystite (exsudative) (hémorragique) (purulente) (suppurée) (à), syphilitique (tardive)  [synonyme]
    - Dacryocystite (aiguë) (phlegmoneuse) (subaiguë), syphilitique (tardive)  [synonyme]
    - Dactylite, syphilitique (tardive)  [synonyme]
    - Destruction (de), cloison (nasale) syphilitique  [synonyme]
    - Destruction (de), os, syphilitique  [synonyme]
    - Déformation (acquise) (système ostéo-articulaire) (de), nez, syphilitique (congénitale), tardive  [synonyme]
    - Epididymite (aiguë) (non sexuellement transmissible) (récidivante) (résiduelle) (due à), syphilitique (tardive)  [synonyme]
    - Episclérite, syphilitique (tardive)  [synonyme]
    - Exostose (osseuse) (de), syphilitique  [synonyme]
    - Fibrose (de), testicule, chronique, due à la syphilis  [synonyme]
    - Gastrite (simple) (à), syphilitique  [synonyme]
    - Glaucome, syphilitique  [synonyme]
    - Glomérulonéphrite (à), au cours de (voir aussi glomérulopathie, au cours de), syphilis  [synonyme]
    - Glomérulopathie (à) (voir aussi glomérulonéphrite), au cours de (voir aussi glomérulonéphrite, au cours de), syphilis  [synonyme]
    - Gomme (syphilitique) (de) (voir aussi syphilis)  [synonyme]
    - Gomme (syphilitique) (de) (voir aussi syphilis), localisation précisée nca  [synonyme]
    - Gomme (syphilitique) (de) (voir aussi syphilis), os  [synonyme]
    - Gomme (syphilitique) (de) (voir aussi syphilis), paupière  [synonyme]
    - Hydarthrose, syphilitique (tardive)  [synonyme]
    - Hémianopsie (binasale) (bitemporale) (hétéronyme) (homonyme) (nasale) (périphérique), syphilitique (tardive)  [synonyme]
    - Hémorragie (de) (due à), vitré (corps), syphilitique  [synonyme]
    - Hépatite (à) (au cours de), consécutive à, syphilis (tardive)  [synonyme]
    - Hépatite (à) (au cours de), syphilitique (tardive)  [synonyme]
    - Iridocyclite, syphilitique (précoce) (secondaire), tardive  [synonyme]
    - Iritis (voir aussi iridocyclite), syphilitique (précoce) (secondaire), tardive  [synonyme]
    - Labyrinthite (circonscrite) (destructrice) (diffuse) (latente) (oreille interne) (purulente) (séreuse) (suppurée), syphilitique  [synonyme]
    - Laryngite (aiguë) (oedémateuse) (sous-glottique) (suppurée) (ulcéreuse) (due à), syphilitique (tardive)  [synonyme]
    … (+111 de plus)
  APHP_DERMATOLOGIE (3) :
    - Gommes syphilitiques  [synonyme]
    - Syphilis symptomatique tardive (autre)  [synonyme]
    - Syphilis tertiaire : autres formes  [synonyme]

── BLOC 3 : RELATIONS DAGUE/ASTÉRISQUE ───────────────────────────────
  • A52.7 est dague (†) ; apparié à H19.0 — sclérite et épisclérite au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A52.7 est dague (†) ; apparié à H32.0 — affections choriorétiniennes au cours de maladies infectieuses et parasitaires classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A52.7 est dague (†) ; apparié à H58.8 — autres affections précisées de l'oeil et de ses annexes au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A52.7 est dague (†) ; apparié à J99.8 — troubles respiratoires au cours d'autres maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A52.7 est dague (†) ; apparié à K67.2 — péritonite syphilitique
      redundancy_level=subordinate ; levels_present=['G', 'U']
  • A52.7 est dague (†) ; apparié à K77.0 — atteintes hépatiques au cours de maladies infectieuses et parasitaires classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A52.7 est dague (†) ; apparié à L99.8 — autres affections précisées de la peau et du tissu cellulaire sous-cutané au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A52.7 est dague (†) ; apparié à M63.0 — myosite au cours de maladies bactériennes classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A52.7 est dague (†) ; apparié à M68.0 — synovite et ténosynovite au cours de maladies bactériennes classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A52.7 est dague (†) ; apparié à M73.1 — bursite syphilitique
      redundancy_level=subordinate ; levels_present=['G', 'U']
  • A52.7 est dague (†) ; apparié à M90.2 — ostéopathie au cours d'autres maladies infectieuses classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A52.7 est dague (†) ; apparié à N08.0 — glomérulopathie au cours de maladies infectieuses et parasitaires classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A52.7 est dague (†) ; apparié à N29.0 — syphilis tardive du rein
      redundancy_level=subordinate ; levels_present=['G']
  • A52.7 est dague (†) ; apparié à N74.2 — affection inflammatoire pelvienne syphilitique de la femme
      redundancy_level=subordinate ; levels_present=['G', 'U']

── BLOC 4 : RÉSULTAT FINAL (CSV) ─────────────────────────────────────
  2478 ligne(s). Répartition par (type, source) :
    synonyme   | CIM-10 index                 : 2100
    synonyme   | CIM-10                       : 210
    exclusion  | CIM-10                       : 42
    synonyme   | AP-HP Dermatologie           : 42
    exclusion  | ANS                          : 28
    inclusion  | ANS                          : 28
    synonyme   | ANS                          : 28

  Détail (type | source | source_level | inherited_from | texte) :
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | code     |           | Affection inflammatoire des organes pelviens de la
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    … (+2438 lignes de plus)

In [6]:
inspect_code(["A18.1", "N33.0"], ctx=ctx)

╔════════════════════════════════════════════════════════════════════╗
║ A18.1 — Tuberculose de l'appareil génito-urinaire                  ║
╚════════════════════════════════════════════════════════════════════╝

── BLOC 1 : IDENTITÉ ─────────────────────────────────────────────────
Code         : A18.1
Libellé OFS  : tuberculose de l'appareil génito-urinaire
Libellé ANS  : Tuberculose de l'appareil génito-urinaire
Type         : category
Chapitre     : I — Certaines maladies infectieuses et parasitaires
Bloc         : A15-A19 — Tuberculose
Catégorie    : A18 — Tuberculose d'autres organes

── BLOC 2 : SOURCES BRUTES (avant fusion) ────────────────────────────
[OFS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Descripteurs / synonymes :
    - tuberculose (de) uretère
    - tuberculose (de) vessie
    - tuberculose (de) organes génitaux de l'homme
    - tuberculose (de) col de l'utérus
    - tuberculose (de) rénale
    - affection inflammatoire tuberculeuse des organes pelviens de la femme
  Notes éditoriales :
    (aucune entrée)

[ANS]
  Inclusions :
    - Affection inflammatoire tuberculeuse des organes pelviens de la femme [N74.1]
Tuberculose (de) :
 - col de l'utérus [N74.0]
 - organes génitaux de l'homme [N51.-]
 - rénale [N29.1]
 - uretère [N29.1]
 - vessie [N33.0]

  Exclusions :
    (aucune entrée)
  Synonymes :
    - Affection inflammatoire tuberculeuse des organes pelviens de la femme
    - Tuberculose (de) col de l'utérus
    - Tuberculose (de) vessie
    - Tuberculose (de) uretère
    - Tuberculose (de) rénale
    - Tuberculose (de) organes génitaux de l'homme
  Notes (définitions / scope) :
    (aucune entrée)

[SOURCES EXTERNES]
  ORPHANET (2) :
    - Tuberculose génito-urinaire primaire  [synonyme, E]
    - Tuberculose urogénitale  [synonyme, E]
  INDEX_CIM10_VOL3 (91) :
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), glande(s) (de), bulbo-urétrale(s), tuberculeux  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), glande(s) (de), cowper, tuberculeux  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), pelvien, femme, tuberculeux  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), périnéphrétique, tuberculeux  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, glande de cowper  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, génito-urinaire (femme)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, pelvien (femme)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, périnéphrétique  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, rein  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, scrotum  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, testicule  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, utérus  [synonyme]
    - Adhérences (post-infectieuses) (de), pelviennes, pelvi-péritonéales (homme) (voir aussi adhérences, péritonéales), tuberculeuses  [synonyme]
    - Bacillurie (voir aussi bactériurie), tuberculeuse  [synonyme]
    - Cervicite (aiguë) (avec ectropion ou érosion du col) (chronique) (non sexuellement transmissible) (subaiguë) (à), tuberculeuse  [synonyme]
    - Cystite (exsudative) (hémorragique) (purulente) (suppurée) (à), tuberculeuse  [synonyme]
    - Déférentite (à), tuberculeuse  [synonyme]
    - Endométrite (infectieuse) (non spécifique) (purulente) (suppurée) (à), tuberculeuse  [synonyme]
    - Epididymite (aiguë) (non sexuellement transmissible) (récidivante) (résiduelle) (due à), tuberculeuse  [synonyme]
    - Fistule (de), scrotum (urinaire), tuberculeuse  [synonyme]
    - Fistule (de), urètre, tuberculeuse  [synonyme]
    - Fistule (de), épididyme, tuberculeuse  [synonyme]
    - Funiculite (aiguë) (chronique) (endémique) (à), tuberculeuse  [synonyme]
    - Glomérulonéphrite (à), au cours de (voir aussi glomérulopathie, au cours de), tuberculose  [synonyme]
    - Hydronéphrose (atrophique) (intermittente) (primitive) (secondaire), tuberculeuse  [synonyme]
    - Hématurie (essentielle), tuberculeuse  [synonyme]
    - Infection (à) (de), urinaire (voies), tuberculeuse  [synonyme]
    - Kyste (colloïde) (muqueux) (séreux) (de), ovaire, ovarien (adhérent) (d'involution) (hémorragique) (rétentionnel) (séreux) (tordu) nca, tuberculeux  [synonyme]
    - Maladie (à) (de) rein (bassinet) (fonctionnelle), au cours de, tuberculose  [synonyme]
    - Métrite (infectieuse) (purulente) (à) (voir aussi endométrite), tuberculeuse  [synonyme]
    - Néphrite (à) (voir aussi syndrome, néphritique), au cours de, tuberculose  [synonyme]
    - Néphrite (à) (voir aussi syndrome, néphritique), tuberculeuse  [synonyme]
    - Néphrite (à) (voir aussi syndrome, néphritique), tubulo-interstitielle (voir aussi trouble, tubulo- interstitiel), tuberculeuse  [synonyme]
    - Néphropathie, au cours de (voir aussi glomérulopathie, au cours de), tuberculose  [synonyme]
    - Orchite (aiguë) (gangréneuse) (infectée) (suppurée) (à), tuberculeuse  [synonyme]
    - Ovarite (infectieuse) (interstitielle) (kystique) (à), tuberculeuse  [synonyme]
    - Prostatite (congestive) (suppurée) (à), tuberculeuse  [synonyme]
    - Pyélite (à) (voir aussi pyélonéphrite), tuberculeuse  [synonyme]
    - Pyélonéphrite (voir aussi pyélite), tuberculeuse  [synonyme]
    - Rétrécissement (de) - voir aussi sténose, trompe (de), fallope, tuberculeux  [synonyme]
    … (+51 de plus)
  APHP_NEPHROLOGIE (1) :
    - tuberculose génito-urinaire [coder d'abord 1141NL à 1144NL]  [synonyme]

── BLOC 3 : RELATIONS DAGUE/ASTÉRISQUE ───────────────────────────────
  • A18.1 est dague (†) ; apparié à N29.1 — autres affections du rein et de l'uretère au cours de maladies infectieuses et parasitaires classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A18.1 est dague (†) ; apparié à N33.0 — cystite tuberculeuse
      redundancy_level=subordinate ; levels_present=['G', 'U']
  • A18.1 est dague (†) ; apparié à N51 — affections des organes génitaux de l'homme au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['U']
  • A18.1 est dague (†) ; apparié à N51.0 — affections de la prostate au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['H']
  • A18.1 est dague (†) ; apparié à N51.1 — affections du testicule et de l'épididyme au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['H']
  • A18.1 est dague (†) ; apparié à N51.8 — autres affections des organes génitaux de l'homme au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['H']
  • A18.1 est dague (†) ; apparié à N74.0 — tuberculose du col de l'utérus
      redundancy_level=subordinate ; levels_present=['G', 'U']
  • A18.1 est dague (†) ; apparié à N74.1 — affection inflammatoire pelvienne tuberculeuse de la femme
      redundancy_level=independent ; levels_present=['G', 'U']
  • A18.1 est dague (†) ; apparié à N77.0 — ulcération de la vulve au cours de maladies infectieuses et parasitaires classées ailleurs
      redundancy_level=subordinate ; levels_present=['H']
  • A18.1 est dague (†) ; apparié à (aucun) —
      redundancy_level=none ; levels_present=['S']

── BLOC 4 : RÉSULTAT FINAL (CSV) ─────────────────────────────────────
  954 ligne(s). Répartition par (type, source) :
    synonyme   | CIM-10 index                 : 792
    synonyme   | CIM-10                       : 54
    exclusion  | CIM-10                       : 36
    exclusion  | ANS                          : 18
    inclusion  | ANS                          : 18
    synonyme   | ORPHANET                     : 18
    inclusion  | CIM-10                       : 9
    synonyme   | AP-HP Néphrologie            : 9

  Détail (type | source | source_level | inherited_from | texte) :
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | code     |           | Affection inflammatoire tuberculeuse des organes p
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | block    | A15-A19   | immunodéficience humaine virale [VIH] à l'origine
    exclusion | ANS                    | block    | A15-A19   | immunodéficience humaine virale [VIH] à l'origine
    exclusion | ANS                    | block    | A15-A19   | immunodéficience humaine virale [VIH] à l'origine
    exclusion | ANS                    | block    | A15-A19   | immunodéficience humaine virale [VIH] à l'origine
    … (+914 lignes de plus)


╔════════════════════════════════════════════════════════════════════╗
║ N33.0 — Cystite tuberculeuse                                       ║
╚════════════════════════════════════════════════════════════════════╝

── BLOC 1 : IDENTITÉ ─────────────────────────────────────────────────
Code         : N33.0
Libellé OFS  : cystite tuberculeuse
Libellé ANS  : Cystite tuberculeuse
Type         : category
Chapitre     : XIV — Maladies de l'appareil génito-urinaire
Bloc         : N30-N39 — Autres maladies de l'appareil urinaire
Catégorie    : N33 — Affections de la vessie au cours de maladies classées ailleurs

── BLOC 2 : SOURCES BRUTES (avant fusion) ────────────────────────────
[OFS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Descripteurs / synonymes :
    (aucune entrée)
  Notes éditoriales :
    (aucune entrée)

[ANS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Synonymes :
    (aucune entrée)
  Notes (définitions / scope) :
    (aucune entrée)

[SOURCES EXTERNES]
  APHP_NEPHROLOGIE (1) :
    - tuberculose vésicale [coder aussi 1145NL]  [synonyme]

── BLOC 3 : RELATIONS DAGUE/ASTÉRISQUE ───────────────────────────────
  • N33.0 est astérisque (*) ; apparié à A18.1 — tuberculose de l'appareil génito-urinaire
      redundancy_level=subordinate ; levels_present=['G', 'U']

── BLOC 4 : RÉSULTAT FINAL (CSV) ─────────────────────────────────────
  6 ligne(s). Répartition par (type, source) :
    exclusion  | CIM-10                       : 3
    exclusion  | ANS                          : 2
    synonyme   | AP-HP Néphrologie            : 1

  Détail (type | source | source_level | inherited_from | texte) :
    exclusion | ANS                    | chapter  | XIV       | certaines affections dont l'origine se situe dans
    exclusion | ANS                    | block    | N30-N39   | infection urinaire (compliquant) :
 - avec lithias
    exclusion | CIM-10                 | block    | N30-N39   | infection urinaire (compliquant) avec lithiase uri
    exclusion | CIM-10                 | block    | N30-N39   | infection urinaire (compliquant) avortement, gross
    exclusion | CIM-10                 | block    | N30-N39   | infection urinaire (compliquant) grossesse, accouc
    synonyme  | AP-HP Néphrologie      | code     |           | tuberculose vésicale [coder aussi 1145NL]

In [7]:
inspect_code("A18", ctx=ctx)

╔════════════════════════════════════════════════════════════════════╗
║ A18.0 — Tuberculose des os et des articulations                    ║
╚════════════════════════════════════════════════════════════════════╝

── BLOC 1 : IDENTITÉ ─────────────────────────────────────────────────
Code         : A18.0
Libellé OFS  : tuberculose des os et des articulations
Libellé ANS  : Tuberculose des os et des articulations
Type         : category
Chapitre     : I — Certaines maladies infectieuses et parasitaires
Bloc         : A15-A19 — Tuberculose
Catégorie    : A18 — Tuberculose d'autres organes

── BLOC 2 : SOURCES BRUTES (avant fusion) ────────────────────────────
[OFS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Descripteurs / synonymes :
    - tuberculose de genou [tumeur blanche du genou]
    - arthrite tuberculeuse
    - mastoïdite tuberculeuse
    - ostéite tuberculeuse
    - ostéomyélite tuberculeuse
    - ostéonécrose tuberculeuse
    - synovite tuberculeuse
    - ténosynovite tuberculeuse
    - tuberculose de colonne vertébrale [mal de Pott]
    - tuberculose de hanche
  Notes éditoriales :
    (aucune entrée)

[ANS]
  Inclusions :
    - Arthrite [M01.1]   tuberculeuse
Mastoïdite [H75.0]   tuberculeuse
Ostéite [M90.0]   tuberculeuse
Ostéomyélite [M90.0]   tuberculeuse
Ostéonécrose [M90.0]   tuberculeuse
Synovite [M68.0]   tuberculeuse
Ténosynovite [M68.0]   tuberculeuse
Tuberculose de :
 - colonne vertébrale [mal de Pott] [M49.0]
 - genou [tumeur blanche du genou] [M01.1]
 - hanche [M01.1]

  Exclusions :
    (aucune entrée)
  Synonymes :
    - Tuberculose de colonne vertébrale [mal de Pott]
    - Ostéonécrose tuberculeuse
    - Ostéomyélite tuberculeuse
    - Ostéite tuberculeuse
    - Mastoïdite tuberculeuse
    - Ténosynovite tuberculeuse
    - Synovite tuberculeuse
    - Tuberculose de genou [tumeur blanche du genou]
    - Arthrite tuberculeuse
    - Tuberculose de hanche
  Notes (définitions / scope) :
    (aucune entrée)

[SOURCES EXTERNES]
  INDEX_CIM10_VOL3 (111) :
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), colonne vertébrale (tuberculeux)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), froid (ostéo-articulaire)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), genou, articulation (voir aussi arthrite, selon le germe), tuberculeux (évolutif)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), hanche, articulation (voir aussi arthrite, selon le germe), tuberculeux (évolutif)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), lombaire (région), tuberculeux (vertébral)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), os (sous-périoste) (sauf sinus de la face et mastoïde) (voir aussi ostéite et ostéomyélite), colonne vertébrale (évolutif) (tuberculeux)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), psoas (évolutif) (tuberculeux)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), sacrum (tuberculeux)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, articulaire  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, articulaire, vertébral  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, colonne vertébrale  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, genou (articulation)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, hanche (articulation)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, lombaire  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, os, osseux  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, os, osseux, colonne vertébrale  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, os, osseux, sacrum  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, os, osseux, vertèbres  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, psoas(-iliaque)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, sacrum  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, sinus paranasal, partie osseuse  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, vertébral, vertèbres  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), vertèbre (tuberculeux)  [synonyme]
    - Affection (à) (de) - voir aussi maladie, organe(s) (voir aussi affection, selon l'organe), pelviens (femme), inflammatoire (à) (due à) (voir aussi maladie, pelvienne, inflammatoire), tuberculeuse  [synonyme]
    - Arthrite (aiguë) (chronique) (subaiguë) (à) (de) (voir aussi arthropathie), colonne vertébrale, tuberculeuse  [synonyme]
    - Arthrite (aiguë) (chronique) (subaiguë) (à) (de) (voir aussi arthropathie), tuberculeuse  [synonyme]
    - Arthrite (aiguë) (chronique) (subaiguë) (à) (de) (voir aussi arthropathie), tuberculeuse, vertébrale  [synonyme]
    - Arthrite (aiguë) (chronique) (subaiguë) (à) (de) (voir aussi arthropathie), vertébrale (de), tuberculeuse  [synonyme]
    - Arthropathie (à) (de) (voir aussi arthrite), associée à, au cours de, due à (voir aussi arthropathie, réactionnelle), maladie(s) (de), tuberculeuse  [synonyme]
    - Arthropathie (à) (de) (voir aussi arthrite), associée à, au cours de, due à (voir aussi arthropathie, réactionnelle), maladie(s) (de), tuberculeuse, vertébrale  [synonyme]
    - Baker, kyste de, tuberculeux  [synonyme]
    - Chondrite (suppurée), tuberculeuse nca (voir aussi tuberculose, osseuse)  [synonyme]
    - Chondrite (suppurée), tuberculeuse nca (voir aussi tuberculose, osseuse), intervertébrale  [synonyme]
    - Courbure (non rachitique) (osseuse) (de), colonne vertébrale (acquise) (angulaire) (posturale), tuberculeuse  [synonyme]
    - Coxalgie (non tuberculeuse), tuberculeuse  [synonyme]
    - Cyphose (acquise), tuberculeuse (évolutive)  [synonyme]
    - Dactylite, tuberculeuse  [synonyme]
    - Destruction (de), articulation, tuberculeuse  [synonyme]
    - Destruction (de), articulation, tuberculeuse, vertébrale  [synonyme]
    - Destruction (de), os, tuberculeuse  [synonyme]
    … (+71 de plus)

── BLOC 3 : RELATIONS DAGUE/ASTÉRISQUE ───────────────────────────────
  • A18.0 est dague (†) ; apparié à H75.0 — mastoïdite au cours de maladies infectieuses et parasitaires classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A18.0 est dague (†) ; apparié à M01.1 — arthrite tuberculeuse
      redundancy_level=subordinate ; levels_present=['G', 'U']
  • A18.0 est dague (†) ; apparié à M49.0 — tuberculose vertébrale
      redundancy_level=subordinate ; levels_present=['G', 'U']
  • A18.0 est dague (†) ; apparié à M68.0 — synovite et ténosynovite au cours de maladies bactériennes classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A18.0 est dague (†) ; apparié à M90.0 — tuberculose osseuse
      redundancy_level=subordinate ; levels_present=['G', 'U']
  • A18.0 est dague (†) ; apparié à (aucun) —
      redundancy_level=none ; levels_present=['S']

── BLOC 4 : RÉSULTAT FINAL (CSV) ─────────────────────────────────────
  640 ligne(s). Répartition par (type, source) :
    synonyme   | CIM-10 index                 : 545
    synonyme   | CIM-10                       : 50
    exclusion  | CIM-10                       : 20
    exclusion  | ANS                          : 10
    inclusion  | ANS                          : 10
    inclusion  | CIM-10                       : 5

  Détail (type | source | source_level | inherited_from | texte) :
    inclusion | ANS                    | code     |           | Arthrite [M01.1]   tuberculeuse
Mastoïdite [H75.0]
    inclusion | ANS                    | code     |           | Arthrite [M01.1]   tuberculeuse
Mastoïdite [H75.0]
    inclusion | ANS                    | code     |           | Arthrite [M01.1]   tuberculeuse
Mastoïdite [H75.0]
    inclusion | ANS                    | code     |           | Arthrite [M01.1]   tuberculeuse
Mastoïdite [H75.0]
    inclusion | ANS                    | code     |           | Arthrite [M01.1]   tuberculeuse
Mastoïdite [H75.0]
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    inclusion | CIM-10                 | block    | A15-A19   | infections à Mycobacterium tuberculosis et Mycobac
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | block    | A15-A19   | immunodéficience humaine virale [VIH] à l'origine
    exclusion | ANS                    | block    | A15-A19   | immunodéficience humaine virale [VIH] à l'origine
    exclusion | ANS                    | block    | A15-A19   | immunodéficience humaine virale [VIH] à l'origine
    exclusion | ANS                    | block    | A15-A19   | immunodéficience humaine virale [VIH] à l'origine
    exclusion | ANS                    | block    | A15-A19   | immunodéficience humaine virale [VIH] à l'origine
    exclusion | CIM-10                 | block    | A15-A19   | pneumoconiose associée à une tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | pneumoconiose associée à une tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | pneumoconiose associée à une tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | pneumoconiose associée à une tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | pneumoconiose associée à une tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | silico-tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | silico-tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | silico-tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | silico-tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | silico-tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | séquelles de tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | séquelles de tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | séquelles de tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | séquelles de tuberculose
    exclusion | CIM-10                 | block    | A15-A19   | séquelles de tuberculose
    … (+600 lignes de plus)


╔════════════════════════════════════════════════════════════════════╗
║ A18.1 — Tuberculose de l'appareil génito-urinaire                  ║
╚════════════════════════════════════════════════════════════════════╝

── BLOC 1 : IDENTITÉ ─────────────────────────────────────────────────
Code         : A18.1
Libellé OFS  : tuberculose de l'appareil génito-urinaire
Libellé ANS  : Tuberculose de l'appareil génito-urinaire
Type         : category
Chapitre     : I — Certaines maladies infectieuses et parasitaires
Bloc         : A15-A19 — Tuberculose
Catégorie    : A18 — Tuberculose d'autres organes

── BLOC 2 : SOURCES BRUTES (avant fusion) ────────────────────────────
[OFS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Descripteurs / synonymes :
    - tuberculose (de) uretère
    - tuberculose (de) vessie
    - tuberculose (de) organes génitaux de l'homme
    - tuberculose (de) col de l'utérus
    - tuberculose (de) rénale
    - affection inflammatoire tuberculeuse des organes pelviens de la femme
  Notes éditoriales :
    (aucune entrée)

[ANS]
  Inclusions :
    - Affection inflammatoire tuberculeuse des organes pelviens de la femme [N74.1]
Tuberculose (de) :
 - col de l'utérus [N74.0]
 - organes génitaux de l'homme [N51.-]
 - rénale [N29.1]
 - uretère [N29.1]
 - vessie [N33.0]

  Exclusions :
    (aucune entrée)
  Synonymes :
    - Affection inflammatoire tuberculeuse des organes pelviens de la femme
    - Tuberculose (de) col de l'utérus
    - Tuberculose (de) vessie
    - Tuberculose (de) uretère
    - Tuberculose (de) rénale
    - Tuberculose (de) organes génitaux de l'homme
  Notes (définitions / scope) :
    (aucune entrée)

[SOURCES EXTERNES]
  ORPHANET (2) :
    - Tuberculose génito-urinaire primaire  [synonyme, E]
    - Tuberculose urogénitale  [synonyme, E]
  INDEX_CIM10_VOL3 (91) :
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), glande(s) (de), bulbo-urétrale(s), tuberculeux  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), glande(s) (de), cowper, tuberculeux  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), pelvien, femme, tuberculeux  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), périnéphrétique, tuberculeux  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, glande de cowper  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, génito-urinaire (femme)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, pelvien (femme)  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, périnéphrétique  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, rein  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, scrotum  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, testicule  [synonyme]
    - Abcès (embolique) (infectieux) (multiple) (pyogène) (septique) (de), tuberculeux, utérus  [synonyme]
    - Adhérences (post-infectieuses) (de), pelviennes, pelvi-péritonéales (homme) (voir aussi adhérences, péritonéales), tuberculeuses  [synonyme]
    - Bacillurie (voir aussi bactériurie), tuberculeuse  [synonyme]
    - Cervicite (aiguë) (avec ectropion ou érosion du col) (chronique) (non sexuellement transmissible) (subaiguë) (à), tuberculeuse  [synonyme]
    - Cystite (exsudative) (hémorragique) (purulente) (suppurée) (à), tuberculeuse  [synonyme]
    - Déférentite (à), tuberculeuse  [synonyme]
    - Endométrite (infectieuse) (non spécifique) (purulente) (suppurée) (à), tuberculeuse  [synonyme]
    - Epididymite (aiguë) (non sexuellement transmissible) (récidivante) (résiduelle) (due à), tuberculeuse  [synonyme]
    - Fistule (de), scrotum (urinaire), tuberculeuse  [synonyme]
    - Fistule (de), urètre, tuberculeuse  [synonyme]
    - Fistule (de), épididyme, tuberculeuse  [synonyme]
    - Funiculite (aiguë) (chronique) (endémique) (à), tuberculeuse  [synonyme]
    - Glomérulonéphrite (à), au cours de (voir aussi glomérulopathie, au cours de), tuberculose  [synonyme]
    - Hydronéphrose (atrophique) (intermittente) (primitive) (secondaire), tuberculeuse  [synonyme]
    - Hématurie (essentielle), tuberculeuse  [synonyme]
    - Infection (à) (de), urinaire (voies), tuberculeuse  [synonyme]
    - Kyste (colloïde) (muqueux) (séreux) (de), ovaire, ovarien (adhérent) (d'involution) (hémorragique) (rétentionnel) (séreux) (tordu) nca, tuberculeux  [synonyme]
    - Maladie (à) (de) rein (bassinet) (fonctionnelle), au cours de, tuberculose  [synonyme]
    - Métrite (infectieuse) (purulente) (à) (voir aussi endométrite), tuberculeuse  [synonyme]
    - Néphrite (à) (voir aussi syndrome, néphritique), au cours de, tuberculose  [synonyme]
    - Néphrite (à) (voir aussi syndrome, néphritique), tuberculeuse  [synonyme]
    - Néphrite (à) (voir aussi syndrome, néphritique), tubulo-interstitielle (voir aussi trouble, tubulo- interstitiel), tuberculeuse  [synonyme]
    - Néphropathie, au cours de (voir aussi glomérulopathie, au cours de), tuberculose  [synonyme]
    - Orchite (aiguë) (gangréneuse) (infectée) (suppurée) (à), tuberculeuse  [synonyme]
    - Ovarite (infectieuse) (interstitielle) (kystique) (à), tuberculeuse  [synonyme]
    - Prostatite (congestive) (suppurée) (à), tuberculeuse  [synonyme]
    - Pyélite (à) (voir aussi pyélonéphrite), tuberculeuse  [synonyme]
    - Pyélonéphrite (voir aussi pyélite), tuberculeuse  [synonyme]
    - Rétrécissement (de) - voir aussi sténose, trompe (de), fallope, tuberculeux  [synonyme]
    … (+51 de plus)
  APHP_NEPHROLOGIE (1) :
    - tuberculose génito-urinaire [coder d'abord 1141NL à 1144NL]  [synonyme]

── BLOC 3 : RELATIONS DAGUE/ASTÉRISQUE ───────────────────────────────
  • A18.1 est dague (†) ; apparié à N29.1 — autres affections du rein et de l'uretère au cours de maladies infectieuses et parasitaires classées ailleurs
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • A18.1 est dague (†) ; apparié à N33.0 — cystite tuberculeuse
      redundancy_level=subordinate ; levels_present=['G', 'U']
  • A18.1 est dague (†) ; apparié à N51 — affections des organes génitaux de l'homme au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['U']
  • A18.1 est dague (†) ; apparié à N51.0 — affections de la prostate au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['H']
  • A18.1 est dague (†) ; apparié à N51.1 — affections du testicule et de l'épididyme au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['H']
  • A18.1 est dague (†) ; apparié à N51.8 — autres affections des organes génitaux de l'homme au cours de maladies classées ailleurs
      redundancy_level=subordinate ; levels_present=['H']
  • A18.1 est dague (†) ; apparié à N74.0 — tuberculose du col de l'utérus
      redundancy_level=subordinate ; levels_present=['G', 'U']
  • A18.1 est dague (†) ; apparié à N74.1 — affection inflammatoire pelvienne tuberculeuse de la femme
      redundancy_level=independent ; levels_present=['G', 'U']
  • A18.1 est dague (†) ; apparié à N77.0 — ulcération de la vulve au cours de maladies infectieuses et parasitaires classées ailleurs

In [8]:
# inspect_code("E10.2", ctx=ctx)

In [9]:
# %% A01.0 — Cas fil rouge du diagnostic dague/astérisque
inspect_code("A01.0", verbose=True)

╔════════════════════════════════════════════════════════════════════╗
║ A01.0 — Fièvre typhoïde                                            ║
╚════════════════════════════════════════════════════════════════════╝

── BLOC 1 : IDENTITÉ ─────────────────────────────────────────────────
Code         : A01.0
Libellé OFS  : fièvre typhoïde
Libellé ANS  : Fièvre typhoïde
Type         : category
Chapitre     : I — Certaines maladies infectieuses et parasitaires
Bloc         : A00-A09 — Maladies intestinales infectieuses
Catégorie    : A01 — Fièvres typhoïde et paratyphoïde

── BLOC 2 : SOURCES BRUTES (avant fusion) ────────────────────────────
[OFS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Descripteurs / synonymes :
    - infection due à Salmonella typhi
  Notes éditoriales :
    (aucune entrée)

[ANS]
  Inclusions :
    - Infection due à Salmonella typhi

  Exclusions :
    (aucune entrée)
  Synonymes :
    - Infection due à Salmonella typhi
  Notes (définitions / scope) :
    (aucune entrée)

[SOURCES EXTERNES]
  ORPHANET (2) :
    - Fièvre typhoïde  [synonyme, E]
    - Typhoïde  [synonyme, E]
  INDEX_CIM10_VOL3 (29) :
    - Adénite (de), mésentérique (aiguë) (chronique) (non spécifique) (subaiguë), bacille d'eberth  [synonyme]
    - Arthropathie (à) (de) (voir aussi arthrite), associée à, au cours de, due à (voir aussi arthropathie, réactionnelle), fièvre, typhoïde  [synonyme]
    - Arthropathie (à) (de) (voir aussi arthrite), associée à, au cours de, due à (voir aussi arthropathie, réactionnelle), typhoïde  [synonyme]
    - Eberth, maladie d'  [synonyme]
    - Endocardite (chronique) (non bactérienne) (thrombosante) (valvulaire) (à) (de) (due à), typhoïdique  [synonyme]
    - Entérite (aiguë) (diarrhéique) (épidémique) (présumée infectieuse) (due à) (voir aussi note à la catégorie, typhoïdique  [synonyme]
    - Fièvre (de) (des) (due à), typhoïde (abortive) (asymptomatique) (hémorragique) (latente)  [synonyme]
    - Fièvre (de) (des) (due à), typhoïde (abortive) (asymptomatique) (hémorragique) (latente), avec, perforation gastro-intestinale  [synonyme]
    - Fièvre (de) (des) (due à), typhoïde (abortive) (asymptomatique) (hémorragique) (latente), avec, perforation gastro-intestinale, avec péritonite  [synonyme]
    - Fièvre (de) (des) (due à), typhoïde (abortive) (asymptomatique) (hémorragique) (latente), avec, pneumopathie  [synonyme]
    - Infection (à) (de), bacille ou bacillus (de), eberth  [synonyme]
    - Infection (à) (de), salmonella (arizonae) (cholerae-suis) (enteritidis) (typhimurium), typhi  [synonyme]
    - Infection (à) (de), salmonella (arizonae) (cholerae-suis) (enteritidis) (typhimurium), typhosa  [synonyme]
    - Infection (à) (de), typhique, au sens de, typhoïde  [synonyme]
    - Infection (à) (de), typhoïde, typhoïdique  [synonyme]
    - Lymphadénite (à), mésentérique (aiguë) (chronique) (non spécifique) (subaiguë), due à, salmonella typhi  [synonyme]
    - Myocardite (ancienne) (chronique) (fibreuse) (interstitielle) (progressive) (sénile) (à) (de), au cours de, fièvre typhoïde  [synonyme]
    - Myocardite (ancienne) (chronique) (fibreuse) (interstitielle) (progressive) (sénile) (à) (de), typhoïdique  [synonyme]
    - Méningite (basilaire) (cérébrale) (spinale) (à), au cours de (voir aussi méningite, selon l'affection), fièvre typhoïde  [synonyme]
    - Méningite (basilaire) (cérébrale) (spinale) (à), typhoïdique  [synonyme]
    - Ostéomyélite (infectieuse) (septique) (suppurée) (à) (de), typhoïdique  [synonyme]
    - Perforation (non traumatique) (de) (due à), typhoïdique gastro-intestinale  [synonyme]
    - Pneumopathie (aiguë) (double) (purulente) (septique) (à) (de), au cours de, fièvre, typhoïde  [synonyme]
    - Pneumopathie (aiguë) (double) (purulente) (septique) (à) (de), au cours de, typhoïde  [synonyme]
    - Péritonite (avec épanchement) (fibrineuse) (à), typhoïdique  [synonyme]
    - Spondylite (de), typhoïdique  [synonyme]
    - Typhopéritonite  [synonyme]
    - Ulcère (à) (de), intestin (primaire) (stercoral) nca, typhoïdique  [synonyme]
    - Ulcère (à) (de), typhoïdique (perforant)  [synonyme]
  APHP_GERMES (1) :
    - Salmonella Typhi  [synonyme]

── BLOC 2bis : DONNÉES BRUTES (DEBUG) ────────────────────────────────
[OFS — Tables brutes liées au SID]
  MASTER  : 1 ligne — SID=8, code=A01.0, type=S, level=4, abbrev=A010
  LIBELLE : 3 ligne(s)
    SID=8 | LID=8 | source=S | valid=1 | libelle=fièvre typhoïde
    SID=8 | LID=12320 | source=D | valid=1 | libelle=infection due à Salmonella typhi
    SID=8 | LID=32095 | source=D | valid=1
  DESCR   : 2 ligne(s)
    SID=8 | LID=12320 | libelle=infection due à Salmonella typhi
    SID=8 | LID=32095
  DAGSTAR : 3 ligne(s)
    SID=2910 | assoc=8 | daget=H | plus=0
    SID=3922 | assoc=8 | daget=H | plus=0
    SID=4285 | assoc=8 | daget=H | plus=0

[ANS — Propriétés agrégées (owl_codes.parquet)]
  rdfs:label          : Fièvre typhoïde
  dc:type             : category
  inclusion_note      : Infection due à Salmonella typhi

  synonymes           : (1 valeur(s))
    - Infection due à Salmonella typhi

── BLOC 3 : RELATIONS DAGUE/ASTÉRISQUE ───────────────────────────────
  • A01.0 est dague (†) ; apparié à G01 — méningite au cours d'affections bactériennes classées ailleurs
      redundancy_level=independent ; levels_present=['H']
  • A01.0 est dague (†) ; apparié à I39 — endocardite et atteintes valvulaires cardiaques au cours de maladies classées ailleurs
      redundancy_level=independent ; levels_present=['H']
  • A01.0 est dague (†) ; apparié à J17.0 — pneumopathie au cours de maladies bactériennes classées ailleurs
      redundancy_level=independent ; levels_present=['H']

── BLOC 4 : RÉSULTAT FINAL (CSV) ─────────────────────────────────────
  108 ligne(s). Répartition par (type, source) :
    synonyme   | CIM-10 index                 : 87
    inclusion  | ANS                          : 6
    synonyme   | ORPHANET                     : 6
    exclusion  | ANS                          : 3
    synonyme   | AP-HP Germes (SPILF)         : 3
    synonyme   | CIM-10                       : 3

  Détail (type | source | source_level | inherited_from | texte) :
    inclusion | ANS                    | code     |           | Infection due à Salmonella typhi

    inclusion | ANS                    | code     |           | Infection due à Salmonella typhi

    inclusion | ANS                    | code     |           | Infection due à Salmonella typhi

    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    synonyme  | AP-HP Germes (SPILF)   | code     |           | Salmonella Typhi
    synonyme  | AP-HP Germes (SPILF)   | code     |           | Salmonella Typhi
    synonyme  | AP-HP Germes (SPILF)   | code     |           | Salmonella Typhi
    synonyme  | CIM-10                 | code     |           | infection due à Salmonella typhi
    synonyme  | CIM-10                 | code     |           | infection due à Salmonella typhi
    synonyme  | CIM-10                 | code     |           | infection due à Salmonella typhi
    synonyme  | CIM-10 index           | code     |           | Adénite (de), mésentérique (aiguë) (chronique) (no
    synonyme  | CIM-10 index           | code     |           | Adénite (de), mésentérique (aiguë) (chronique) (no
    synonyme  | CIM-10 index           | code     |           | Adénite (de), mésentérique (aiguë) (chronique) (no
    synonyme  | CIM-10 index           | code     |           | Arthropathie (à) (de) (voir aussi arthrite), assoc
    synonyme  | CIM-10 index           | code     |           | Arthropathie (à) (de) (voir aussi arthrite), assoc
    synonyme  | CIM-10 index           | code     |           | Arthropathie (à) (de) (voir aussi arthrite), assoc
    synonyme  | CIM-10 index           | code     |           | Arthropathie (à) (de) (voir aussi arthrite), assoc
    synonyme  | CIM-10 index           | code     |           | Arthropathie (à) (de) (voir aussi arthrite), assoc
    synonyme  | CIM-10 index           | code     |           | Arthropathie (à) (de) (voir aussi arthrite), assoc
    synonyme  | CIM-10 index           | code     |           | Eberth, maladie d'
    synonyme  | CIM-10 index           | code     |           | Eberth, maladie d'
    synonyme  | CIM-10 index           | code     |           | Eberth, maladie d'
    synonyme  | CIM-10 index           | code     |           | Endocardite (chronique) (non bactérienne) (thrombo
    synonyme  | CIM-10 index           | code     |           | Endocardite (chronique) (non bactérienne) (thrombo
    synonyme  | CIM-10 index           | code     |           | Endocardite (chronique) (non bactérienne) (thrombo
    synonyme  | CIM-10 index           | code     |           | Entérite (aiguë) (diarrhéique) (épidémique) (présu
    synonyme  | CIM-10 index           | code     |           | Entérite (aiguë) (diarrhéique) (épidémique) (présu
    synonyme  | CIM-10 index           | code     |           | Entérite (aiguë) (diarrhéique) (épidémique) (présu
    synonyme  | CIM-10 index           | code     |           | Fièvre (de) (des) (due à), typhoïde (abortive) (as
    synonyme  | CIM-10 index           | code     |           | Fièvre (de) (des) (due à), typhoïde (abortive) (as
    synonyme  | CIM-10 index           | code     |           | Fièvre (de) (des) (due à), typhoïde (abortive) (as
    synonyme  | CIM-10 index           | code     |           | Fièvre (de) (des) (due à), typhoïde (abortive) (as
    synonyme  | CIM-10 index           | code     |           | Fièvre (de) (des) (due à), typhoïde (abortive) (as
    synonyme  | CIM-10 index           | code     |           | Fièvre (de) (des) (due à), typhoïde (abortive) (as
    synonyme  | CIM-10 index           | code     |           | Fièvre (de) (des) (due à), typhoïde (abortive) (as
    … (+68 lignes de plus)

── BLOC 5 : PARCOURS DANS LE PIPELINE (DEBUG) ────────────────────────
  Étape                    | Nb lignes                  | Variation
  -------------------------|----------------------------|----------
  RDF ANS brut (triples)   | (non chargé — coût ~3,5 s) |
  ofs_codes.parquet        | 1                          |
  owl_codes.parquet        | 1                          |
  merged_codes.parquet     | 1                          |
  propagated_notes.parquet | 3                          | Δ1 = +2 (propagation)
  flat_csv (CSV final)     | 108                        | Δ2 = +105 (expansion + synonymes + externes)

  → Δ1 = 2 : héritage hiérarchique détecté.
  → Δ2 = 105 : 3 paire(s) dague/astérisque impliquant A01.0 → expansion attendue, plus synonymes/externes.

  Traçage des 5 texte(s) dupliqué(s) dans flat_csv
  (textes transitant par propagated_notes affichés en premier — le saut N→M y révèle l'expansion) :

    "Infection due à Salmonella typhi\n"
      owl_codes=1 | merged_codes=1 | propagated_notes=1 | flat_csv=3

    "certaines infections localisées – voir les chapitres relatif"
      owl_codes=0 | merged_codes=0 | propagated_notes=1 | flat_csv=3

    "les maladies considérées habituellement comme contagieuses o"
      owl_codes=0 | merged_codes=0 | propagated_notes=1 | flat_csv=3

    "Adénite (de), mésentérique (aiguë) (chronique) (non spécifiq"
      owl_codes=0 | merged_codes=0 | propagated_notes=0 | flat_csv=3

    "Arthropathie (à) (de) (voir aussi arthrite), associée à, au "
      owl_codes=0 | merged_codes=0 | propagated_notes=0 | flat_csv=3

In [12]:
inspect_code("G01",verbose=True)

╔════════════════════════════════════════════════════════════════════╗
║ G01 — Méningite au cours d'affections bactériennes classées ailleu ║
║ rs                                                                 ║
╚════════════════════════════════════════════════════════════════════╝

── BLOC 1 : IDENTITÉ ─────────────────────────────────────────────────
Code         : G01
Libellé OFS  : méningite au cours d'affections bactériennes classées ailleurs
Libellé ANS  : Méningite au cours d'affections bactériennes classées ailleurs
Type         : category
Chapitre     : VI — Maladies du système nerveux
Bloc         : G00-G09 — Maladies inflammatoires du système nerveux central
Catégorie    : G01 — Méningite au cours d'affections bactériennes classées ailleurs

── BLOC 2 : SOURCES BRUTES (avant fusion) ────────────────────────────
[OFS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    - méningo-encéphalite et méningomyélite au cours d'affections bactériennes classées ailleurs
  Descripteurs / synonymes :
    - méningite (au cours de) listérienne
    - méningite (au cours de) tuberculeuse
    - méningite (au cours de) syphilitique secondaire
    - méningite (au cours de) syphilitique congénitale
    - méningite (au cours de) neurosyphilis
    - méningite (au cours de) leptospirose
    - méningite (au cours de) maladie de Lyme
    - méningite (au cours de) infection à Salmonella
    - méningite (au cours de) gonococcique
    - méningite (au cours de) fièvre typhoïde
    - méningite (au cours de) charbonneuse
    - méningite (au cours de) méningococcique
  Notes éditoriales :
    (aucune entrée)

[ANS]
  Inclusions :
    - Méningite (au cours de) :
 - charbonneuse [A22.8]
 - fièvre typhoïde [A01.0]
 - gonococcique [A54.8]
 - infection à Salmonella [A02.2]
 - leptospirose [A27.-]
 - listérienne [A32.1]
 - maladie de Lyme [A69.2]
 - méningococcique [A39.0]
 - neurosyphilis [A52.1]
 - syphilitique :
  - congénitale [A50.4]
  - secondaire [A51.4]
 - tuberculeuse [A17.0]

  Exclusions :
    - méningoencéphalite et méningomyélite au cours d'affections bactériennes classées ailleurs [G05.0]

  Synonymes :
    - Méningite (au cours de) listérienne
    - Méningite (au cours de) syphilitique congénitale
    - Méningite (au cours de) neurosyphilis
    - Méningite (au cours de) tuberculeuse
    - Méningite (au cours de) charbonneuse
    - Méningite (au cours de) infection à Salmonella
    - Méningite (au cours de) méningococcique
    - Méningite (au cours de) fièvre typhoïde
    - Méningite (au cours de) gonococcique
    - Méningite (au cours de) syphilitique secondaire
    - Méningite (au cours de) leptospirose
    - Méningite (au cours de) maladie de Lyme
  Notes (définitions / scope) :
    (aucune entrée)

[SOURCES EXTERNES]
    (aucune entrée externe pour ce code)

── BLOC 2bis : DONNÉES BRUTES (DEBUG) ────────────────────────────────
[OFS — Tables brutes liées au SID]
  MASTER  : 1 ligne — SID=2910, code=G01, type=K, level=3, abbrev=G01
  LIBELLE : 14 ligne(s)
    SID=2910 | LID=3329 | source=S | valid=1 | libelle=méningite au cours d'affections bactériennes classées ailleurs
    SID=2910 | LID=15296 | source=D | valid=1 | libelle=méningite (au cours de) listérienne
    SID=2910 | LID=15297 | source=D | valid=1 | libelle=méningite (au cours de) tuberculeuse
    SID=2910 | LID=15298 | source=D | valid=1 | libelle=méningite (au cours de) syphilitique secondaire
    SID=2910 | LID=15299 | source=D | valid=1 | libelle=méningite (au cours de) syphilitique congénitale
    SID=2910 | LID=15300 | source=D | valid=1 | libelle=méningite (au cours de) neurosyphilis
    SID=2910 | LID=15301 | source=D | valid=1 | libelle=méningite (au cours de) leptospirose
    SID=2910 | LID=15302 | source=D | valid=1 | libelle=méningite (au cours de) maladie de Lyme
    … (+6 ligne(s) de plus)
  EXCLUDE : 1 ligne(s)
    SID=2910 | LID=29813 | excl=2928 | plus=0 | daget=T | libelle=méningo-encéphalite et méningomyélite au cours d'affections bactéri…
  DESCR   : 12 ligne(s)
    SID=2910 | LID=15296 | libelle=méningite (au cours de) listérienne
    SID=2910 | LID=15297 | libelle=méningite (au cours de) tuberculeuse
    SID=2910 | LID=15298 | libelle=méningite (au cours de) syphilitique secondaire
    SID=2910 | LID=15299 | libelle=méningite (au cours de) syphilitique congénitale
    SID=2910 | LID=15300 | libelle=méningite (au cours de) neurosyphilis
    SID=2910 | LID=15301 | libelle=méningite (au cours de) leptospirose
    SID=2910 | LID=15302 | libelle=méningite (au cours de) maladie de Lyme
    SID=2910 | LID=15303 | libelle=méningite (au cours de) infection à Salmonella
    … (+4 ligne(s) de plus)
  DAGSTAR : 22 ligne(s)
    SID=2910 | assoc=160 | daget=H | plus=1
    SID=285 | assoc=2910 | daget=U | plus=0
    SID=302 | assoc=2910 | daget=U | plus=0
    SID=16 | assoc=2910 | daget=U | plus=0
    SID=94 | assoc=2910 | daget=T | plus=0
    SID=136 | assoc=2910 | daget=U | plus=0
    SID=187 | assoc=2910 | daget=U | plus=0
    SID=208 | assoc=2910 | daget=T | plus=0
    … (+14 ligne(s) de plus)

[ANS — Propriétés agrégées (owl_codes.parquet)]
  rdfs:label          : Méningite au cours d'affections bactériennes classées ailleurs
  dc:type             : category
  inclusion_note      : Méningite (au cours de) :
       - charbonneuse [A22.8]
       - fièvre typhoïde [A01.0]
       - gonococcique [A54.8]
       - infection à Salmonella [A02.2]
       - leptospirose [A27.-]
       - listérienne [A32.1]
       - maladie de Lyme [A69.2]
       - méningococcique [A39.0]
       -
  synonymes           : (12 valeur(s))
    - Méningite (au cours de) listérienne
    - Méningite (au cours de) syphilitique congénitale
    - Méningite (au cours de) neurosyphilis
    - Méningite (au cours de) tuberculeuse
    - Méningite (au cours de) charbonneuse
    - Méningite (au cours de) infection à Salmonella
    - Méningite (au cours de) méningococcique
    - Méningite (au cours de) fièvre typhoïde
    … (+4 de plus)
  exclusion_notes     : (1 valeur(s))
    - méningoencéphalite et méningomyélite au cours d'affections bactériennes classées ailleurs [G05.0]

  structured_exclusions: (1 valeur(s))
    - http://data.esante.gouv.fr/atih/cim10/G05.0

── BLOC 3 : RELATIONS DAGUE/ASTÉRISQUE ───────────────────────────────
  • G01 est astérisque (*) ; apparié à A01.0 — fièvre typhoïde
      redundancy_level=independent ; levels_present=['H']
  • G01 est astérisque (*) ; apparié à A02.2 — infection localisée à Salmonella
      redundancy_level=independent ; levels_present=['H', 'U']
  • G01 est astérisque (*) ; apparié à A17.0 — méningite tuberculeuse
      redundancy_level=subordinate ; levels_present=['H', 'T']
  • G01 est astérisque (*) ; apparié à A22.8 — autres formes de charbon
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • G01 est astérisque (*) ; apparié à A27 — leptospirose
      redundancy_level=subordinate ; levels_present=['H']
  • G01 est astérisque (*) ; apparié à A32.1 — méningite et méningo-encéphalite listériennes
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • G01 est astérisque (*) ; apparié à A39.0 — méningite à méningocoques
      redundancy_level=subordinate ; levels_present=['H', 'T']
  • G01 est astérisque (*) ; apparié à A50.4 — syphilis congénitale nerveuse tardive [neuro-syphilis juvénile]
      redundancy_level=independent ; levels_present=['H', 'U']
  • G01 est astérisque (*) ; apparié à A51.4 — autres formes de syphilis secondaire
      redundancy_level=independent ; levels_present=['H', 'U']
  • G01 est astérisque (*) ; apparié à A52.1 — syphilis nerveuse symptomatique
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • G01 est astérisque (*) ; apparié à A54.8 — autres infections gonococciques
      redundancy_level=subordinate ; levels_present=['H', 'U']
  • G01 est astérisque (*) ; apparié à A69.2 — maladie de Lyme
      redundancy_level=independent ; levels_present=['H']
  • G01 est astérisque (*) ; apparié à (aucun) —
      redundancy_level=none ; levels_present=['F']

── BLOC 4 : RÉSULTAT FINAL (CSV) ─────────────────────────────────────
  192 ligne(s). Répartition par (type, source) :
    synonyme   | CIM-10                       : 144
    exclusion  | ANS                          : 24
    exclusion  | CIM-10                       : 12
    inclusion  | ANS                          : 12

  Détail (type | source | source_level | inherited_from | texte) :
    inclusion | ANS                    | code     |           | Méningite (au cours de) :
 - charbonneuse [A22.8]
    inclusion | ANS                    | code     |           | Méningite (au cours de) :
 - charbonneuse [A22.8]
    inclusion | ANS                    | code     |           | Méningite (au cours de) :
 - charbonneuse [A22.8]
    inclusion | ANS                    | code     |           | Méningite (au cours de) :
 - charbonneuse [A22.8]
    inclusion | ANS                    | code     |           | Méningite (au cours de) :
 - charbonneuse [A22.8]
    inclusion | ANS                    | code     |           | Méningite (au cours de) :
 - charbonneuse [A22.8]
    inclusion | ANS                    | code     |           | Méningite (au cours de) :
 - charbonneuse [A22.8]
    inclusion | ANS                    | code     |           | Méningite (au cours de) :
 - charbonneuse [A22.8]
    inclusion | ANS                    | code     |           | Méningite (au cours de) :
 - charbonneuse [A22.8]
    inclusion | ANS                    | code     |           | Méningite (au cours de) :
 - charbonneuse [A22.8]
    inclusion | ANS                    | code     |           | Méningite (au cours de) :
 - charbonneuse [A22.8]
    inclusion | ANS                    | code     |           | Méningite (au cours de) :
 - charbonneuse [A22.8]
    exclusion | ANS                    | chapter  | VI        | certaines affections dont l'origine se situe dans
    exclusion | ANS                    | chapter  | VI        | certaines affections dont l'origine se situe dans
    exclusion | ANS                    | chapter  | VI        | certaines affections dont l'origine se situe dans
    exclusion | ANS                    | chapter  | VI        | certaines affections dont l'origine se situe dans
    exclusion | ANS                    | chapter  | VI        | certaines affections dont l'origine se situe dans
    exclusion | ANS                    | chapter  | VI        | certaines affections dont l'origine se situe dans
    exclusion | ANS                    | chapter  | VI        | certaines affections dont l'origine se situe dans
    exclusion | ANS                    | chapter  | VI        | certaines affections dont l'origine se situe dans
    exclusion | ANS                    | chapter  | VI        | certaines affections dont l'origine se situe dans
    exclusion | ANS                    | chapter  | VI        | certaines affections dont l'origine se situe dans
    exclusion | ANS                    | chapter  | VI        | certaines affections dont l'origine se situe dans
    exclusion | ANS                    | chapter  | VI        | certaines affections dont l'origine se situe dans
    exclusion | ANS                    | code     |           | méningoencéphalite et méningomyélite au cours d'af
    exclusion | ANS                    | code     |           | méningoencéphalite et méningomyélite au cours d'af
    exclusion | ANS                    | code     |           | méningoencéphalite et méningomyélite au cours d'af
    exclusion | ANS                    | code     |           | méningoencéphalite et méningomyélite au cours d'af
    exclusion | ANS                    | code     |           | méningoencéphalite et méningomyélite au cours d'af
    exclusion | ANS                    | code     |           | méningoencéphalite et méningomyélite au cours d'af
    exclusion | ANS                    | code     |           | méningoencéphalite et méningomyélite au cours d'af
    exclusion | ANS                    | code     |           | méningoencéphalite et méningomyélite au cours d'af
    exclusion | ANS                    | code     |           | méningoencéphalite et méningomyélite au cours d'af
    exclusion | ANS                    | code     |           | méningoencéphalite et méningomyélite au cours d'af
    exclusion | ANS                    | code     |           | méningoencéphalite et méningomyélite au cours d'af
    exclusion | ANS                    | code     |           | méningoencéphalite et méningomyélite au cours d'af
    exclusion | CIM-10                 | code     |           | méningo-encéphalite et méningomyélite au cours d'a
    exclusion | CIM-10                 | code     |           | méningo-encéphalite et méningomyélite au cours d'a
    exclusion | CIM-10                 | code     |           | méningo-encéphalite et méningomyélite au cours d'a
    exclusion | CIM-10                 | code     |           | méningo-encéphalite et méningomyélite au cours d'a
    … (+152 lignes de plus)

── BLOC 5 : PARCOURS DANS LE PIPELINE (DEBUG) ────────────────────────
  Étape                    | Nb lignes                  | Variation
  -------------------------|----------------------------|----------
  RDF ANS brut (triples)   | (non chargé — coût ~3,5 s) |
  ofs_codes.parquet        | 1                          |
  owl_codes.parquet        | 1                          |
  merged_codes.parquet     | 1                          |
  propagated_notes.parquet | 4                          | Δ1 = +3 (propagation)
  flat_csv (CSV final)     | 192                        | Δ2 = +188 (expansion + synonymes + externes)

  → Δ1 = 3 : héritage hiérarchique détecté.
  → Δ2 = 188 : 13 paire(s) dague/astérisque impliquant G01 → expansion attendue, plus synonymes/externes.

  Traçage des 5 texte(s) dupliqué(s) dans flat_csv
  (textes transitant par propagated_notes affichés en premier — le saut N→M y révèle l'expansion) :

    "Méningite (au cours de) :\n - charbonneuse [A22.8] \n - fièv"
      owl_codes=1 | merged_codes=1 | propagated_notes=1 | flat_csv=12

    "certaines affections dont l'origine se situe dans la période"
      owl_codes=0 | merged_codes=0 | propagated_notes=1 | flat_csv=12

    "méningo-encéphalite et méningomyélite au cours d'affections "
      owl_codes=0 | merged_codes=1 | propagated_notes=1 | flat_csv=12

    "méningoencéphalite et méningomyélite au cours d'affections b"
      owl_codes=1 | merged_codes=1 | propagated_notes=1 | flat_csv=12

    "méningite (au cours de) charbonneuse"
      owl_codes=0 | merged_codes=1 | propagated_notes=0 | flat_csv=12

In [14]:
inspect_code("A27",verbose= True)

╔════════════════════════════════════════════════════════════════════╗
║ A27.0 — Leptospirose ictérohémorragique                            ║
╚════════════════════════════════════════════════════════════════════╝

── BLOC 1 : IDENTITÉ ─────────────────────────────────────────────────
Code         : A27.0
Libellé OFS  : leptospirose ictéro-hémorragique
Libellé ANS  : Leptospirose ictérohémorragique
Type         : category
Chapitre     : I — Certaines maladies infectieuses et parasitaires
Bloc         : A20-A28 — Certaines anthropozoonoses  bactériennes
Catégorie    : A27 — Leptospirose

── BLOC 2 : SOURCES BRUTES (avant fusion) ────────────────────────────
[OFS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Descripteurs / synonymes :
    - leptospirose à Leptospira interrogans serovar icterohaemorrhagiae
  Notes éditoriales :
    (aucune entrée)

[ANS]
  Inclusions :
    - Leptospirose à Leptospira interrogans serovar icterohaemorrhagiae

  Exclusions :
    (aucune entrée)
  Synonymes :
    - Leptospirose à Leptospira interrogans serovar icterohaemorrhagiae
  Notes (définitions / scope) :
    (aucune entrée)

[SOURCES EXTERNES]
  INDEX_CIM10_VOL3 (13) :
    - Fiedler, maladie de  [synonyme]
    - Ictère (de), hémorragique (aigu) (leptospire) (spirochète)  [synonyme]
    - Ictère (de), infectieux (aigu ou subaigu) - voir aussi hépatite, a, leptospire  [synonyme]
    - Ictère (de), infectieux (aigu ou subaigu) - voir aussi hépatite, a, spirochète  [synonyme]
    - Ictère (de), leptospire  [synonyme]
    - Ictère (de), spirochète (hémorragique)  [synonyme]
    - Ictère (de), épidémique - voir aussi hépatite, a, leptospire  [synonyme]
    - Ictère (de), épidémique - voir aussi hépatite, a, spirochète  [synonyme]
    - Infection (à) (de), leptospira interrogans (serovar), icterohaemorragiae  [synonyme]
    - Leptospirose, due à leptospira interrogans serovar icterohaemorrhagiae  [synonyme]
    - Leptospirose, ictéro-hémorragique  [synonyme]
    - Spirochétose, ictéro-hémorragique  [synonyme]
    - Weil et mathieu, maladie de  [synonyme]

── BLOC 2bis : DONNÉES BRUTES (DEBUG) ────────────────────────────────
[OFS — Tables brutes liées au SID]
  MASTER  : 1 ligne — SID=161, code=A27.0, type=S, level=4, abbrev=A270
  LIBELLE : 2 ligne(s)
    SID=161 | LID=161 | source=S | valid=1 | libelle=leptospirose ictéro-hémorragique
    SID=161 | LID=12512 | source=D | valid=1 | libelle=leptospirose à Leptospira interrogans serovar icterohaemorrhagiae
  DESCR   : 1 ligne(s)
    SID=161 | LID=12512 | libelle=leptospirose à Leptospira interrogans serovar icterohaemorrhagiae

[ANS — Propriétés agrégées (owl_codes.parquet)]
  rdfs:label          : Leptospirose ictérohémorragique
  dc:type             : category
  inclusion_note      : Leptospirose à Leptospira interrogans serovar icterohaemorrhagiae

  synonymes           : (1 valeur(s))
    - Leptospirose à Leptospira interrogans serovar icterohaemorrhagiae

── BLOC 3 : RELATIONS DAGUE/ASTÉRISQUE ───────────────────────────────
    (pas d'association dague/astérisque)

── BLOC 4 : RÉSULTAT FINAL (CSV) ─────────────────────────────────────
  17 ligne(s). Répartition par (type, source) :
    synonyme   | CIM-10 index                 : 13
    inclusion  | ANS                          : 2
    exclusion  | ANS                          : 1
    synonyme   | CIM-10                       : 1

  Détail (type | source | source_level | inherited_from | texte) :
    inclusion | ANS                    | code     |           | Leptospirose à Leptospira interrogans serovar icte
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    synonyme  | CIM-10                 | code     |           | leptospirose à Leptospira interrogans serovar icte
    synonyme  | CIM-10 index           | code     |           | Fiedler, maladie de
    synonyme  | CIM-10 index           | code     |           | Ictère (de), hémorragique (aigu) (leptospire) (spi
    synonyme  | CIM-10 index           | code     |           | Ictère (de), infectieux (aigu ou subaigu) - voir a
    synonyme  | CIM-10 index           | code     |           | Ictère (de), infectieux (aigu ou subaigu) - voir a
    synonyme  | CIM-10 index           | code     |           | Ictère (de), leptospire
    synonyme  | CIM-10 index           | code     |           | Ictère (de), spirochète (hémorragique)
    synonyme  | CIM-10 index           | code     |           | Ictère (de), épidémique - voir aussi hépatite, a,
    synonyme  | CIM-10 index           | code     |           | Ictère (de), épidémique - voir aussi hépatite, a,
    synonyme  | CIM-10 index           | code     |           | Infection (à) (de), leptospira interrogans (serova
    synonyme  | CIM-10 index           | code     |           | Leptospirose, due à leptospira interrogans serovar
    synonyme  | CIM-10 index           | code     |           | Leptospirose, ictéro-hémorragique
    synonyme  | CIM-10 index           | code     |           | Spirochétose, ictéro-hémorragique
    synonyme  | CIM-10 index           | code     |           | Weil et mathieu, maladie de

── BLOC 5 : PARCOURS DANS LE PIPELINE (DEBUG) ────────────────────────
  Étape                    | Nb lignes                  | Variation
  -------------------------|----------------------------|----------
  RDF ANS brut (triples)   | (non chargé — coût ~3,5 s) |
  ofs_codes.parquet        | 1                          |
  owl_codes.parquet        | 1                          |
  merged_codes.parquet     | 1                          |
  propagated_notes.parquet | 3                          | Δ1 = +2 (propagation)
  flat_csv (CSV final)     | 17                         | Δ2 = +14 (expansion + synonymes + externes)

  → Δ1 = 2 : héritage hiérarchique détecté.
  → Δ2 = 14 : aucune paire dague/astérisque pour A27.0 → Δ2 vient des synonymes et sources externes seuls.


╔════════════════════════════════════════════════════════════════════╗
║ A27.8 — Autres formes de leptospirose                              ║
╚════════════════════════════════════════════════════════════════════╝

── BLOC 1 : IDENTITÉ ─────────────────────────────────────────────────
Code         : A27.8
Libellé OFS  : autres formes de leptospirose
Libellé ANS  : Autres formes de leptospirose
Type         : category
Chapitre     : I — Certaines maladies infectieuses et parasitaires
Bloc         : A20-A28 — Certaines anthropozoonoses  bactériennes
Catégorie    : A27 — Leptospirose

── BLOC 2 : SOURCES BRUTES (avant fusion) ────────────────────────────
[OFS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Descripteurs / synonymes :
    (aucune entrée)
  Notes éditoriales :
    (aucune entrée)

[ANS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Synonymes :
    (aucune entrée)
  Notes (définitions / scope) :
    (aucune entrée)

[SOURCES EXTERNES]
  INDEX_CIM10_VOL3 (12) :
    - Fièvre (de) (des) (due à), automnale du japon  [synonyme]
    - Fièvre (de) (des) (due à), fort bragg  [synonyme]
    - Fièvre (de) (des) (due à), sept jours (japon)  [synonyme]
    - Infection (à) (de), leptospira interrogans (serovar), précisée nca  [synonyme]
    - Leptospirose, canicola  [synonyme]
    - Leptospirose, forme précisée nca  [synonyme]
    - Leptospirose, grippotyphosa  [synonyme]
    - Leptospirose, pomona  [synonyme]
    - Leptospirose, typhogrippale  [synonyme]
    - Maladie (à) (de) porchers  [synonyme]
    - Nanukayami  [synonyme]
    - Spirochétose, grippotyphosa  [synonyme]

── BLOC 2bis : DONNÉES BRUTES (DEBUG) ────────────────────────────────
[OFS — Tables brutes liées au SID]
  MASTER  : 1 ligne — SID=162, code=A27.8, type=S, level=4, abbrev=A278
  LIBELLE : 1 ligne(s)
    SID=162 | LID=162 | source=S | valid=1 | libelle=autres formes de leptospirose

[ANS — Propriétés agrégées (owl_codes.parquet)]
  rdfs:label          : Autres formes de leptospirose
  dc:type             : category

── BLOC 3 : RELATIONS DAGUE/ASTÉRISQUE ───────────────────────────────
    (pas d'association dague/astérisque)

── BLOC 4 : RÉSULTAT FINAL (CSV) ─────────────────────────────────────
  15 ligne(s). Répartition par (type, source) :
    synonyme   | CIM-10 index                 : 12
    exclusion  | ANS                          : 1
    exclusion  | CIM-10 frères                : 1
    inclusion  | ANS                          : 1

  Détail (type | source | source_level | inherited_from | texte) :
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    exclusion | CIM-10 frères          | code     |           | Leptospirose ictérohémorragique (A27.0)
    synonyme  | CIM-10 index           | code     |           | Fièvre (de) (des) (due à), automnale du japon
    synonyme  | CIM-10 index           | code     |           | Fièvre (de) (des) (due à), fort bragg
    synonyme  | CIM-10 index           | code     |           | Fièvre (de) (des) (due à), sept jours (japon)
    synonyme  | CIM-10 index           | code     |           | Infection (à) (de), leptospira interrogans (serova
    synonyme  | CIM-10 index           | code     |           | Leptospirose, canicola
    synonyme  | CIM-10 index           | code     |           | Leptospirose, forme précisée nca
    synonyme  | CIM-10 index           | code     |           | Leptospirose, grippotyphosa
    synonyme  | CIM-10 index           | code     |           | Leptospirose, pomona
    synonyme  | CIM-10 index           | code     |           | Leptospirose, typhogrippale
    synonyme  | CIM-10 index           | code     |           | Maladie (à) (de) porchers
    synonyme  | CIM-10 index           | code     |           | Nanukayami
    synonyme  | CIM-10 index           | code     |           | Spirochétose, grippotyphosa

── BLOC 5 : PARCOURS DANS LE PIPELINE (DEBUG) ────────────────────────
  Étape                    | Nb lignes                  | Variation
  -------------------------|----------------------------|----------
  RDF ANS brut (triples)   | (non chargé — coût ~3,5 s) |
  ofs_codes.parquet        | 1                          |
  owl_codes.parquet        | 1                          |
  merged_codes.parquet     | 1                          |
  propagated_notes.parquet | 2                          | Δ1 = +1 (propagation)
  flat_csv (CSV final)     | 15                         | Δ2 = +13 (expansion + synonymes + externes)

  → Δ1 = 1 : héritage hiérarchique détecté.
  → Δ2 = 13 : aucune paire dague/astérisque pour A27.8 → Δ2 vient des synonymes et sources externes seuls.


╔════════════════════════════════════════════════════════════════════╗
║ A27.9 — Leptospirose, sans précision                               ║
╚════════════════════════════════════════════════════════════════════╝

── BLOC 1 : IDENTITÉ ─────────────────────────────────────────────────
Code         : A27.9
Libellé OFS  : leptospirose, sans précision
Libellé ANS  : Leptospirose, sans précision
Type         : category
Chapitre     : I — Certaines maladies infectieuses et parasitaires
Bloc         : A20-A28 — Certaines anthropozoonoses  bactériennes
Catégorie    : A27 — Leptospirose

── BLOC 2 : SOURCES BRUTES (avant fusion) ────────────────────────────
[OFS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Descripteurs / synonymes :
    (aucune entrée)
  Notes éditoriales :
    (aucune entrée)

[ANS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Synonymes :
    (aucune entrée)
  Notes (définitions / scope) :
    (aucune entrée)

[SOURCES EXTERNES]
  INDEX_CIM10_VOL3 (2) :
    - Infection (à) (de), leptospira interrogans (serovar)  [synonyme]
    - Leptospirose  [synonyme]
  APHP_GERMES (1) :
    - Leptospira  [synonyme]
  APHP_DERMATOLOGIE (1) :
    - Leptospirose SAI  [synonyme]
  APHP_NEPHROLOGIE (1) :
    - leptospirose  [synonyme]

── BLOC 2bis : DONNÉES BRUTES (DEBUG) ────────────────────────────────
[OFS — Tables brutes liées au SID]
  MASTER  : 1 ligne — SID=163, code=A27.9, type=S, level=4, abbrev=A279
  LIBELLE : 1 ligne(s)
    SID=163 | LID=163 | source=S | valid=1 | libelle=leptospirose, sans précision

[ANS — Propriétés agrégées (owl_codes.parquet)]
  rdfs:label          : Leptospirose, sans précision
  dc:type             : category

── BLOC 3 : RELATIONS DAGUE/ASTÉRISQUE ───────────────────────────────
    (pas d'association dague/astérisque)

── BLOC 4 : RÉSULTAT FINAL (CSV) ─────────────────────────────────────
  6 ligne(s). Répartition par (type, source) :
    synonyme   | CIM-10 index                 : 2
    exclusion  | ANS                          : 1
    inclusion  | ANS                          : 1
    synonyme   | AP-HP Dermatologie           : 1
    synonyme   | AP-HP Germes (SPILF)         : 1

  Détail (type | source | source_level | inherited_from | texte) :
    inclusion | ANS                    | chapter  | I         | les maladies considérées habituellement comme cont
    exclusion | ANS                    | chapter  | I         | certaines infections localisées – voir les chapitr
    synonyme  | AP-HP Dermatologie     | code     |           | Leptospirose SAI
    synonyme  | AP-HP Germes (SPILF)   | code     |           | Leptospira
    synonyme  | CIM-10 index           | code     |           | Infection (à) (de), leptospira interrogans (serova
    synonyme  | CIM-10 index           | code     |           | Leptospirose

── BLOC 5 : PARCOURS DANS LE PIPELINE (DEBUG) ────────────────────────
  Étape                    | Nb lignes                  | Variation
  -------------------------|----------------------------|----------
  RDF ANS brut (triples)   | (non chargé — coût ~3,5 s) |
  ofs_codes.parquet        | 1                          |
  owl_codes.parquet        | 1                          |
  merged_codes.parquet     | 1                          |
  propagated_notes.parquet | 2                          | Δ1 = +1 (propagation)
  flat_csv (CSV final)     | 6                          | Δ2 = +4 (expansion + synonymes + externes)

  → Δ1 = 1 : héritage hiérarchique détecté.
  → Δ2 = 4 : aucune paire dague/astérisque pour A27.9 → Δ2 vient des synonymes et sources externes seuls.

In [25]:
inspect_code("J18.8", verbose=True)

╔════════════════════════════════════════════════════════════════════╗
║ J18.8 — Autres pneumopathies, microorganisme non précisé           ║
╚════════════════════════════════════════════════════════════════════╝

── BLOC 1 : IDENTITÉ ─────────────────────────────────────────────────
Code         : J18.8
Libellé OFS  : autres pneumopathies, micro-organisme non précisé
Libellé ANS  : Autres pneumopathies, microorganisme non précisé
Type         : category
Chapitre     : X — Maladies de l'appareil respiratoire
Bloc         : J09-J18 — Grippe et pneumopathie
Catégorie    : J18 — Pneumopathie à microorganisme non précisé

── BLOC 2 : SOURCES BRUTES (avant fusion) ────────────────────────────
[OFS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Descripteurs / synonymes :
    (aucune entrée)
  Notes éditoriales :
    (aucune entrée)

[ANS]
  Inclusions :
    (aucune entrée)
  Exclusions :
    (aucune entrée)
  Synonymes :
    (aucune entrée)
  Notes (définitions / scope) :
    (aucune entrée)

[SOURCES EXTERNES]
  INDEX_CIM10_VOL3 (3) :
    - Pleuropneumonie (aiguë) (bilatérale) (septique) (voir aussi pneumopathie)  [synonyme]
    - Pleuropneumopathie (aiguë) (bilatérale) (septique) (voir aussi pneumopathie)  [synonyme]
    - Pneumopathie, congénitale, précisée nca  [synonyme]

── BLOC 2bis : DONNÉES BRUTES (DEBUG) ────────────────────────────────
[OFS — Tables brutes liées au SID]
  MASTER  : 1 ligne — SID=4294, code=J18.8, type=S, level=4, abbrev=J188
  LIBELLE : 1 ligne(s)
    SID=4294 | LID=4653 | source=S | valid=1 | libelle=autres pneumopathies, micro-organisme non précisé

[ANS — Propriétés agrégées (owl_codes.parquet)]
  rdfs:label          : Autres pneumopathies, microorganisme non précisé
  dc:type             : category

── BLOC 3 : RELATIONS DAGUE/ASTÉRISQUE ───────────────────────────────
    (pas d'association dague/astérisque)

── BLOC 4 : RÉSULTAT FINAL (CSV) ─────────────────────────────────────
  19 ligne(s). Répartition par (type, source) :
    exclusion  | CIM-10                       : 11
    exclusion  | CIM-10 frères                : 3
    synonyme   | CIM-10 index                 : 3
    exclusion  | ANS                          : 2

  Détail (type | source | source_level | inherited_from | texte) :
    exclusion | ANS                    | category | J18       | abcès du poumon avec pneumopathie [J85.1]
affectio
    exclusion | ANS                    | chapter  | X         | certaines affections dont l'origine se situe dans
    exclusion | CIM-10                 | category | J18       | abcès du poumon avec pneumopathie
    exclusion | CIM-10                 | category | J18       | affections pulmonaires interstitielles médicamente
    exclusion | CIM-10                 | category | J18       | pneumopathie (par) aspiration due à une anesthésie
    exclusion | CIM-10                 | category | J18       | pneumopathie (par) aspiration due à une anesthésie
    exclusion | CIM-10                 | category | J18       | pneumopathie (par) aspiration due à une anesthésie
    exclusion | CIM-10                 | category | J18       | pneumopathie (par) congénitale
    exclusion | CIM-10                 | category | J18       | pneumopathie (par) due à des agents externes
    exclusion | CIM-10                 | category | J18       | pneumopathie (par) inhalation (de)  SAI
    exclusion | CIM-10                 | category | J18       | pneumopathie (par) inhalation (de) huile
    exclusion | CIM-10                 | category | J18       | pneumopathie (par) interstitielle SAI
    exclusion | CIM-10                 | category | J18       | pneumopathie (par) néonatale d'aspiration
    exclusion | CIM-10 frères          | code     |           | Bronchopneumopathie, sans précision (J18.0)
    exclusion | CIM-10 frères          | code     |           | Pneumopathie hypostatique, sans précision (J18.2)
    exclusion | CIM-10 frères          | code     |           | Pneumopathie lobaire, sans précision (J18.1)
    synonyme  | CIM-10 index           | code     |           | Pleuropneumonie (aiguë) (bilatérale) (septique) (v
    synonyme  | CIM-10 index           | code     |           | Pleuropneumopathie (aiguë) (bilatérale) (septique)
    synonyme  | CIM-10 index           | code     |           | Pneumopathie, congénitale, précisée nca

── BLOC 5 : PARCOURS DANS LE PIPELINE (DEBUG) ────────────────────────
  Étape                    | Nb lignes                  | Variation
  -------------------------|----------------------------|----------
  RDF ANS brut (triples)   | (non chargé — coût ~3,5 s) |
  ofs_codes.parquet        | 1                          |
  owl_codes.parquet        | 1                          |
  merged_codes.parquet     | 1                          |
  propagated_notes.parquet | 13                         | Δ1 = +12 (propagation)
  flat_csv (CSV final)     | 19                         | Δ2 = +6 (expansion + synonymes + externes)

  → Δ1 = 12 : héritage hiérarchique détecté.
  → Δ2 = 6 : aucune paire dague/astérisque pour J18.8 → Δ2 vient des synonymes et sources externes seuls.

In [10]:
import polars as pl
ctx = load_exploration_context()
ctx.flat.filter(pl.col("code") == "A01.0").select(
    "type", "source", "texte", "dagger_code", "asterisk_code"
).filter(pl.col("texte").str.contains("Salmonella typhi"))

shape: (6, 5)
┌───────────┬────────┬─────────────────────────────────┬─────────────┬───────────────┐
│ type      ┆ source ┆ texte                           ┆ dagger_code ┆ asterisk_code │
│ ---       ┆ ---    ┆ ---                             ┆ ---         ┆ ---           │
│ str       ┆ str    ┆ str                             ┆ str         ┆ str           │
╞═══════════╪════════╪═════════════════════════════════╪═════════════╪═══════════════╡
│ inclusion ┆ ANS    ┆ Infection due à Salmonella typ… ┆ null        ┆ G01           │
│ inclusion ┆ ANS    ┆ Infection due à Salmonella typ… ┆ null        ┆ I39           │
│ inclusion ┆ ANS    ┆ Infection due à Salmonella typ… ┆ null        ┆ J17.0         │
│ synonyme  ┆ CIM-10 ┆ infection due à Salmonella typ… ┆ null        ┆ G01           │
│ synonyme  ┆ CIM-10 ┆ infection due à Salmonella typ… ┆ null        ┆ I39           │
│ synonyme  ┆ CIM-10 ┆ infection due à Salmonella typ… ┆ null        ┆ J17.0         │
└───────────┴────────┴─────────────────────────────────┴─────────────┴───────────────┘

In [11]:
ctx.flat.filter(pl.col("code") == "A01.0").select(
    "type", "source", "texte", "dagger_code", "asterisk_code"
).filter(pl.col("texte").str.contains("Adénite"))

shape: (3, 5)
┌──────────┬──────────────┬─────────────────────────────────┬─────────────┬───────────────┐
│ type     ┆ source       ┆ texte                           ┆ dagger_code ┆ asterisk_code │
│ ---      ┆ ---          ┆ ---                             ┆ ---         ┆ ---           │
│ str      ┆ str          ┆ str                             ┆ str         ┆ str           │
╞══════════╪══════════════╪═════════════════════════════════╪═════════════╪═══════════════╡
│ synonyme ┆ CIM-10 index ┆ Adénite (de), mésentérique (ai… ┆ null        ┆ G01           │
│ synonyme ┆ CIM-10 index ┆ Adénite (de), mésentérique (ai… ┆ null        ┆ I39           │
│ synonyme ┆ CIM-10 index ┆ Adénite (de), mésentérique (ai… ┆ null        ┆ J17.0         │
└──────────┴──────────────┴─────────────────────────────────┴─────────────┴───────────────┘

In [17]:
ctx = load_exploration_context()
print(ctx.ofs["dagstar"].columns)
print(ctx.ofs["dagstar"].head(10))

['SID', 'LID', 'assoc', 'daget', 'plus']
shape: (10, 5)
┌──────┬───────┬───────┬───────┬──────┐
│ SID  ┆ LID   ┆ assoc ┆ daget ┆ plus │
│ ---  ┆ ---   ┆ ---   ┆ ---   ┆ ---  │
│ i64  ┆ i64   ┆ i64   ┆ str   ┆ i64  │
╞══════╪═══════╪═══════╪═══════╪══════╡
│ 4289 ┆ 16594 ┆ 3760  ┆ H     ┆ 0    │
│ 4507 ┆ 4866  ┆ 5434  ┆ G     ┆ 0    │
│ 4508 ┆ 16799 ┆ 5627  ┆ H     ┆ 0    │
│ 4508 ┆ 16799 ┆ 5628  ┆ H     ┆ 0    │
│ 4508 ┆ 16800 ┆ 5615  ┆ H     ┆ 0    │
│ 4508 ┆ 16803 ┆ 5623  ┆ H     ┆ 0    │
│ 4508 ┆ 16801 ┆ 5629  ┆ H     ┆ 0    │
│ 4508 ┆ 16802 ┆ 5635  ┆ H     ┆ 0    │
│ 4508 ┆ 16804 ┆ 5638  ┆ H     ┆ 0    │
│ 4509 ┆ 16807 ┆ 51    ┆ H     ┆ 0    │
└──────┴───────┴───────┴───────┴──────┘

In [18]:
import polars as pl

# 1. Récupérer le SID de A27 (le code dague leptospirose)
a27_sid = ctx.ofs["master"].filter(pl.col("code") == "A27").select("SID").row(0)[0]
print(f"A27 → SID = {a27_sid}")

# 2. Chercher dans DAGSTAR la ligne où G01 (SID=2910) est associé à A27 (assoc=a27_sid)
ligne = ctx.ofs["dagstar"].filter(
    (pl.col("SID") == 2910) & (pl.col("assoc") == a27_sid)
)
print(ligne)

# 3. Récupérer le libellé du LID trouvé
lid_trouve = ligne.select("LID").row(0)[0]
libelle_lid = ctx.ofs["libelle"].filter(pl.col("LID") == lid_trouve).select("libelle").row(0)[0]
print(f"LID {lid_trouve} → {libelle_lid}")

A27 → SID = 160
shape: (1, 5)
┌──────┬───────┬───────┬───────┬──────┐
│ SID  ┆ LID   ┆ assoc ┆ daget ┆ plus │
│ ---  ┆ ---   ┆ ---   ┆ ---   ┆ ---  │
│ i64  ┆ i64   ┆ i64   ┆ str   ┆ i64  │
╞══════╪═══════╪═══════╪═══════╪══════╡
│ 2910 ┆ 15301 ┆ 160   ┆ H     ┆ 1    │
└──────┴───────┴───────┴───────┴──────┘
LID 15301 → méningite (au cours de) leptospirose

In [19]:
import polars as pl

# 1. Récupérer le SID de A27 (le code dague leptospirose)
a27_sid = ctx.ofs["master"].filter(pl.col("code") == "A27").select("SID").row(0)[0]
print(f"A27 → SID = {a27_sid}")

# 2. Chercher dans DAGSTAR la ligne où G01 (SID=2910) est associé à A27 (assoc=a27_sid)
ligne = ctx.ofs["dagstar"].filter(
    (pl.col("SID") == 2910) & (pl.col("assoc") == a27_sid)
)
print("\nLigne DAGSTAR trouvée :")
print(ligne)

# 3. Récupérer le libellé du LID trouvé
if ligne.height > 0:
    lid_trouve = ligne.select("LID").row(0)[0]
    libelle_lid = ctx.ofs["libelle"].filter(
        pl.col("LID") == lid_trouve
    ).select("libelle").row(0)[0]
    print(f"\nLID {lid_trouve} → {libelle_lid}")
else:
    print("\nAucune ligne DAGSTAR trouvée pour cette paire.")

A27 → SID = 160

Ligne DAGSTAR trouvée :
shape: (1, 5)
┌──────┬───────┬───────┬───────┬──────┐
│ SID  ┆ LID   ┆ assoc ┆ daget ┆ plus │
│ ---  ┆ ---   ┆ ---   ┆ ---   ┆ ---  │
│ i64  ┆ i64   ┆ i64   ┆ str   ┆ i64  │
╞══════╪═══════╪═══════╪═══════╪══════╡
│ 2910 ┆ 15301 ┆ 160   ┆ H     ┆ 1    │
└──────┴───────┴───────┴───────┴──────┘

LID 15301 → méningite (au cours de) leptospirose

# Exploration du contenu de la table DAGSTAR et du recouvrement avec les autres sources d'informations.

In [20]:
import polars as pl

# =====================================================================
# Investigation 1 — Couverture des LID DAGSTAR par les autres tables
# =====================================================================
print("=" * 70)
print("INVESTIGATION 1 — Couverture des LID DAGSTAR")
print("=" * 70)

dagstar = ctx.ofs["dagstar"]
total_dagstar = dagstar.height
total_lid_uniques = dagstar.select("LID").n_unique()
print(f"\nDAGSTAR : {total_dagstar} lignes, {total_lid_uniques} LID uniques")

# LID uniques de DAGSTAR
lid_dagstar = set(dagstar.select("LID").to_series().to_list())

# Couverture par LIBELLE
lid_libelle = set(ctx.ofs["libelle"].select("LID").to_series().to_list())
inter_libelle = lid_dagstar & lid_libelle
print(f"\nLID DAGSTAR présents dans LIBELLE : {len(inter_libelle)} / {len(lid_dagstar)}")
print(f"  (donc {len(lid_dagstar) - len(inter_libelle)} LID DAGSTAR absents de LIBELLE)")

# Couverture par INCLUDE
if "include" in ctx.ofs:
    lid_include = set(ctx.ofs["include"].select("LID").to_series().to_list())
    inter_include = lid_dagstar & lid_include
    print(f"\nLID DAGSTAR présents dans INCLUDE : {len(inter_include)} / {len(lid_dagstar)}")

# Couverture par EXCLUDE
if "exclude" in ctx.ofs:
    lid_exclude = set(ctx.ofs["exclude"].select("LID").to_series().to_list())
    inter_exclude = lid_dagstar & lid_exclude
    print(f"\nLID DAGSTAR présents dans EXCLUDE : {len(inter_exclude)} / {len(lid_dagstar)}")

# Couverture par DESCR
if "descr" in ctx.ofs:
    lid_descr = set(ctx.ofs["descr"].select("LID").to_series().to_list())
    inter_descr = lid_dagstar & lid_descr
    print(f"\nLID DAGSTAR présents dans DESCR : {len(inter_descr)} / {len(lid_dagstar)}")

# LID DAGSTAR couverts par AU MOINS une des tables ci-dessus
unions = lid_libelle
if "include" in ctx.ofs:
    unions = unions | lid_include
if "exclude" in ctx.ofs:
    unions = unions | lid_exclude
if "descr" in ctx.ofs:
    unions = unions | lid_descr
couverts = lid_dagstar & unions
non_couverts = lid_dagstar - unions
print(f"\nLID DAGSTAR couverts par au moins UNE des tables : {len(couverts)} / {len(lid_dagstar)}")
print(f"LID DAGSTAR non couverts (orphans) : {len(non_couverts)}")
if non_couverts:
    print(f"  Exemples : {list(non_couverts)[:5]}")

# =====================================================================
# Investigation 2 — Distribution des LID DAGSTAR par source LIBELLE
# =====================================================================
print("\n" + "=" * 70)
print("INVESTIGATION 2 — Source LIBELLE des LID DAGSTAR")
print("=" * 70)

# Jointure DAGSTAR → LIBELLE pour récupérer le source
dagstar_with_source = dagstar.join(
    ctx.ofs["libelle"].select(["LID", "source"]),
    on="LID",
    how="left",
)
distrib_source = (
    dagstar_with_source
    .group_by("source")
    .agg(pl.len().alias("n"))
    .sort("n", descending=True)
)
print("\nDistribution du source LIBELLE pour les LID de DAGSTAR :")
print(distrib_source)

# Légende : S=systematique, D=descripteur, I=inclusion, E=exclusion, N=note
print("\nLégende habituelle OFS : S=systematique, D=descripteur, I=inclusion, E=exclusion, N=note")

# =====================================================================
# Investigation 3 — Position du LID : côté SID (descripteur) vs côté assoc
# =====================================================================
print("\n" + "=" * 70)
print("INVESTIGATION 3 — Position du LID dans la mécanique dague/astérisque")
print("=" * 70)

# Pour chaque ligne DAGSTAR, le LID est rattaché à un SID (via LIBELLE).
# Vérifier : le LID est-il rattaché au SID (la colonne SID de DAGSTAR) ou à assoc ?

# Jointure LIBELLE pour savoir à quel SID est rattaché chaque LID
# (un LID peut être attaché à plusieurs SID en théorie ; on prend tous les rattachements)
lid_to_sids = (
    ctx.ofs["libelle"]
    .group_by("LID")
    .agg(pl.col("SID").alias("sids_rattaches"))
)

dagstar_check = dagstar.join(lid_to_sids, on="LID", how="left")

# Pour chaque ligne, vérifier si le LID est rattaché au SID (de DAGSTAR) ou à assoc
def position_lid(row):
    if row["sids_rattaches"] is None:
        return "lid_introuvable"
    sids = row["sids_rattaches"]
    if row["SID"] in sids and row["assoc"] in sids:
        return "lid_aux_deux"
    elif row["SID"] in sids:
        return "lid_cote_SID"
    elif row["assoc"] in sids:
        return "lid_cote_assoc"
    else:
        return "lid_ailleurs"

dagstar_check = dagstar_check.with_columns(
    pl.struct(["SID", "assoc", "sids_rattaches"])
    .map_elements(position_lid, return_dtype=pl.String)
    .alias("position_lid")
)
distrib_pos = (
    dagstar_check
    .group_by("position_lid")
    .agg(pl.len().alias("n"))
    .sort("n", descending=True)
)
print("\nPosition du LID par rapport aux SID de la ligne DAGSTAR :")
print(distrib_pos)

# Croiser avec daget pour voir si la position dépend du niveau
print("\nCroisé position_lid × daget :")
distrib_pos_daget = (
    dagstar_check
    .group_by(["daget", "position_lid"])
    .agg(pl.len().alias("n"))
    .sort(["daget", "n"], descending=[False, True])
)
print(distrib_pos_daget)

# =====================================================================
# Synthèse
# =====================================================================
print("\n" + "=" * 70)
print("SYNTHÈSE")
print("=" * 70)
print(f"DAGSTAR : {total_dagstar} lignes, {total_lid_uniques} LID uniques")
print(f"LID couverts par LIBELLE/INCLUDE/EXCLUDE/DESCR : {len(couverts)} ({100*len(couverts)/len(lid_dagstar):.1f}%)")
print(f"LID non couverts : {len(non_couverts)}")
print(f"Distribution source LIBELLE : voir tableau ci-dessus")
print(f"Position du LID : voir tableau ci-dessus")

======================================================================
INVESTIGATION 1 — Couverture des LID DAGSTAR
======================================================================

DAGSTAR : 1352 lignes, 1126 LID uniques

LID DAGSTAR présents dans LIBELLE : 1125 / 1126
  (donc 1 LID DAGSTAR absents de LIBELLE)

LID DAGSTAR présents dans INCLUDE : 8 / 1126

LID DAGSTAR présents dans EXCLUDE : 0 / 1126

LID DAGSTAR présents dans DESCR : 656 / 1126

LID DAGSTAR couverts par au moins UNE des tables : 1125 / 1126
LID DAGSTAR non couverts (orphans) : 1
  Exemples : [13911]

======================================================================
INVESTIGATION 2 — Source LIBELLE des LID DAGSTAR
======================================================================

Distribution du source LIBELLE pour les LID de DAGSTAR :
shape: (4, 2)
┌────────┬─────┐
│ source ┆ n   │
│ ---    ┆ --- │
│ str    ┆ u32 │
╞════════╪═════╡
│ D      ┆ 718 │
│ S      ┆ 625 │
│ I      ┆ 8   │
│ null   ┆ 1   │
└────────┴─────┘

Légende habituelle OFS : S=systematique, D=descripteur, I=inclusion, E=exclusion, N=note

======================================================================
INVESTIGATION 3 — Position du LID dans la mécanique dague/astérisque
======================================================================

Position du LID par rapport aux SID de la ligne DAGSTAR :
shape: (2, 2)
┌─────────────────┬──────┐
│ position_lid    ┆ n    │
│ ---             ┆ ---  │
│ str             ┆ u32  │
╞═════════════════╪══════╡
│ lid_cote_SID    ┆ 1351 │
│ lid_introuvable ┆ 1    │
└─────────────────┴──────┘

Croisé position_lid × daget :
shape: (7, 3)
┌───────┬─────────────────┬─────┐
│ daget ┆ position_lid    ┆ n   │
│ ---   ┆ ---             ┆ --- │
│ str   ┆ str             ┆ u32 │
╞═══════╪═════════════════╪═════╡
│ F     ┆ lid_cote_SID    ┆ 269 │
│ G     ┆ lid_cote_SID    ┆ 263 │
│ H     ┆ lid_cote_SID    ┆ 448 │
│ S     ┆ lid_cote_SID    ┆ 37  │
│ T     ┆ lid_cote_SID    ┆ 56  │
│ U     ┆ lid_cote_SID    ┆ 278 │
│ U     ┆ lid_introuvable ┆ 1   │
└───────┴─────────────────┴─────┘

======================================================================
SYNTHÈSE
======================================================================
DAGSTAR : 1352 lignes, 1126 LID uniques
LID couverts par LIBELLE/INCLUDE/EXCLUDE/DESCR : 1125 (99.9%)
LID non couverts : 1
Distribution source LIBELLE : voir tableau ci-dessus
Position du LID : voir tableau ci-dessus

# INVESTIGATION — LID DAGSTAR avec source=S (libellé systématique)

In [22]:
import polars as pl

# =====================================================================
# Investigation approfondie : les 625 LID DAGSTAR de source=S
# =====================================================================
print("=" * 70)
print("INVESTIGATION — LID DAGSTAR avec source=S (libellé systématique)")
print("=" * 70)

dagstar = ctx.ofs["dagstar"]
libelle = ctx.ofs["libelle"]
master = ctx.ofs["master"]

# Jointure DAGSTAR avec LIBELLE pour récupérer le source
dagstar_with_source = dagstar.join(
    libelle.select(["LID", "source", "libelle"]),
    on="LID",
    how="left",
)

# Filtrer les lignes où le LID a source=S
dag_s = dagstar_with_source.filter(pl.col("source") == "S")
print(f"\nNombre de lignes DAGSTAR avec LID source=S : {dag_s.height}")
print(f"Nombre de LID uniques source=S : {dag_s.select('LID').n_unique()}")

# Distribution par daget
print("\n--- Question 2 : corrélation avec daget ---")
print(dag_s.group_by("daget").agg(pl.len().alias("n")).sort("n", descending=True))

# Comparons aussi avec les LID source=D pour voir la différence
print("\nPour comparaison, distribution daget des LID source=D :")
dag_d = dagstar_with_source.filter(pl.col("source") == "D")
print(dag_d.group_by("daget").agg(pl.len().alias("n")).sort("n", descending=True))

# =====================================================================
# Question 3 — Le LID systématique est-il référencé plusieurs fois ?
# =====================================================================
print("\n--- Question 3 : nombre de paires DAGSTAR par LID source=S ---")
# Pour chaque LID source=S, combien de lignes DAGSTAR pointent vers lui ?
freq_lid_s = (
    dag_s
    .group_by("LID")
    .agg(pl.len().alias("nb_paires"))
    .sort("nb_paires", descending=True)
)
print(f"\nDistribution du nombre de paires par LID source=S :")
print(freq_lid_s.select(
    pl.col("nb_paires").min().alias("min"),
    pl.col("nb_paires").quantile(0.5).alias("median"),
    pl.col("nb_paires").mean().alias("mean"),
    pl.col("nb_paires").max().alias("max"),
))

print("\nTop 10 des LID source=S avec le plus de paires :")
top_lid_s = freq_lid_s.head(10).join(
    libelle.filter(pl.col("source") == "S").select(["LID", "SID", "libelle"]),
    on="LID",
    how="left",
).join(
    master.select(["SID", "code"]),
    on="SID",
    how="left",
)
print(top_lid_s)

# =====================================================================
# Question 1 + 4 — Types de codes concernés et exemples
# =====================================================================
print("\n--- Question 1 : types de codes concernés ---")
# Joindre avec master pour récupérer le code et le type
dag_s_enriched = dag_s.join(
    libelle.select(["LID", "SID"]).rename({"SID": "SID_libelle"}),
    on="LID",
    how="left",
).join(
    master.select(["SID", "code", "type", "level"]).rename({"SID": "SID_libelle"}),
    on="SID_libelle",
    how="left",
)

print("\nDistribution du type de code (master.type) pour les LID source=S de DAGSTAR :")
print(dag_s_enriched.group_by("type").agg(pl.len().alias("n")).sort("n", descending=True))

print("\nDistribution du level (master.level) pour les LID source=S de DAGSTAR :")
print(dag_s_enriched.group_by("level").agg(pl.len().alias("n")).sort("n", descending=True))

# Quelques exemples concrets variés
print("\n--- Question 4 : 10 exemples concrets ---")
echantillon = dag_s_enriched.sample(n=min(10, dag_s_enriched.height), seed=42).select([
    "SID", "LID", "assoc", "daget", "plus", "code", "level"
])
print(echantillon)

# Pour chaque exemple, montrer le libellé et chercher le code associé
print("\n--- Détail des 10 exemples (code principal, libellé, code associé) ---")
for row in echantillon.iter_rows(named=True):
    sid = row["SID"]
    lid = row["LID"]
    assoc = row["assoc"]
    daget = row["daget"]
    plus = row["plus"]
    code = row["code"]
    
    # Libellé du LID
    lib_row = libelle.filter(pl.col("LID") == lid).select("libelle").limit(1)
    libelle_text = lib_row.row(0)[0] if lib_row.height > 0 else "(introuvable)"
    
    # Code de l'assoc
    code_assoc_row = master.filter(pl.col("SID") == assoc).select(["code", "level"]).limit(1)
    code_assoc = code_assoc_row.row(0)[0] if code_assoc_row.height > 0 else f"SID={assoc}"
    
    print(f"\n  Code principal : {code} (SID={sid}, daget={daget}, plus={plus})")
    print(f"  LID {lid} : {libelle_text[:80]}")
    print(f"  Code associé   : {code_assoc} (SID={assoc})")

======================================================================
INVESTIGATION — LID DAGSTAR avec source=S (libellé systématique)
======================================================================

Nombre de lignes DAGSTAR avec LID source=S : 625
Nombre de LID uniques source=S : 458

--- Question 2 : corrélation avec daget ---
shape: (4, 2)
┌───────┬─────┐
│ daget ┆ n   │
│ ---   ┆ --- │
│ str   ┆ u32 │
╞═══════╪═════╡
│ F     ┆ 269 │
│ G     ┆ 263 │
│ T     ┆ 56  │
│ S     ┆ 37  │
└───────┴─────┘

Pour comparaison, distribution daget des LID source=D :
shape: (2, 2)
┌───────┬─────┐
│ daget ┆ n   │
│ ---   ┆ --- │
│ str   ┆ u32 │
╞═══════╪═════╡
│ H     ┆ 440 │
│ U     ┆ 278 │
└───────┴─────┘

--- Question 3 : nombre de paires DAGSTAR par LID source=S ---

Distribution du nombre de paires par LID source=S :
shape: (1, 4)
┌─────┬────────┬──────────┬─────┐
│ min ┆ median ┆ mean     ┆ max │
│ --- ┆ ---    ┆ ---      ┆ --- │
│ u32 ┆ f64    ┆ f64      ┆ u32 │
╞═════╪════════╪══════════╪═════╡
│ 1   ┆ 1.0    ┆ 1.364629 ┆ 34  │
└─────┴────────┴──────────┴─────┘

Top 10 des LID source=S avec le plus de paires :
shape: (10, 5)
┌──────┬───────────┬──────┬─────────────────────────────────┬───────┐
│ LID  ┆ nb_paires ┆ SID  ┆ libelle                         ┆ code  │
│ ---  ┆ ---       ┆ ---  ┆ ---                             ┆ ---   │
│ i64  ┆ u32       ┆ i64  ┆ str                             ┆ str   │
╞══════╪═══════════╪══════╪═════════════════════════════════╪═══════╡
│ 3598 ┆ 34        ┆ 3179 ┆ polynévrite au cours d'autres … ┆ G63.3 │
│ 5848 ┆ 18        ┆ 5909 ┆ ostéoporose au cours de maladi… ┆ M82.1 │
│ 5591 ┆ 11        ┆ 5652 ┆ arthropathie au cours d'autres… ┆ M36.3 │
│ 3492 ┆ 8         ┆ 3073 ┆ syndrome lacunaire moteur pur   ┆ G46.5 │
│ 3495 ┆ 8         ┆ 3076 ┆ autres syndromes vasculaires c… ┆ G46.8 │
│ 3491 ┆ 8         ┆ 3072 ┆ syndrome cérébelleux vasculair… ┆ G46.4 │
│ 3493 ┆ 8         ┆ 3074 ┆ syndrome lacunaire sensitif pu… ┆ G46.6 │
│ 3494 ┆ 8         ┆ 3075 ┆ autres syndromes lacunaires     ┆ G46.7 │
│ 3490 ┆ 8         ┆ 3071 ┆ syndromes vasculaires du tronc… ┆ G46.3 │
│ 3486 ┆ 8         ┆ 3067 ┆ syndromes vasculaires cérébrau… ┆ G46   │
└──────┴───────────┴──────┴─────────────────────────────────┴───────┘

--- Question 1 : types de codes concernés ---

Distribution du type de code (master.type) pour les LID source=S de DAGSTAR :
shape: (2, 2)
┌──────┬─────┐
│ type ┆ n   │
│ ---  ┆ --- │
│ str  ┆ u32 │
╞══════╪═════╡
│ S    ┆ 534 │
│ K    ┆ 91  │
└──────┴─────┘

Distribution du level (master.level) pour les LID source=S de DAGSTAR :
shape: (3, 2)
┌───────┬─────┐
│ level ┆ n   │
│ ---   ┆ --- │
│ i64   ┆ u32 │
╞═══════╪═════╡
│ 4     ┆ 452 │
│ 5     ┆ 93  │
│ 3     ┆ 80  │
└───────┴─────┘

--- Question 4 : 10 exemples concrets ---
shape: (10, 7)
┌──────┬──────┬───────┬───────┬──────┬───────┬───────┐
│ SID  ┆ LID  ┆ assoc ┆ daget ┆ plus ┆ code  ┆ level │
│ ---  ┆ ---  ┆ ---   ┆ ---   ┆ ---  ┆ ---   ┆ ---   │
│ i64  ┆ i64  ┆ i64   ┆ str   ┆ i64  ┆ str   ┆ i64   │
╞══════╪══════╪═══════╪═══════╪══════╪═══════╪═══════╡
│ 5236 ┆ 5175 ┆ 0     ┆ F     ┆ 0    ┆ L62   ┆ 3     │
│ 3070 ┆ 3489 ┆ 4059  ┆ G     ┆ 0    ┆ G46.2 ┆ 4     │
│ 2057 ┆ 2476 ┆ 0     ┆ S     ┆ 0    ┆ E10.2 ┆ 4     │
│ 3751 ┆ 4110 ┆ 0     ┆ F     ┆ 0    ┆ H94.0 ┆ 4     │
│ 4926 ┆ 2225 ┆ 0     ┆ F     ┆ 0    ┆ K77.8 ┆ 4     │
│ 3271 ┆ 3690 ┆ 0     ┆ F     ┆ 0    ┆ G94   ┆ 3     │
│ 5909 ┆ 5848 ┆ 2192  ┆ G     ┆ 0    ┆ M82.1 ┆ 5     │
│ 3323 ┆ 3742 ┆ 0     ┆ F     ┆ 0    ┆ H03.8 ┆ 4     │
│ 499  ┆ 499  ┆ 2929  ┆ T     ┆ 0    ┆ B05.0 ┆ 4     │
│ 6380 ┆ 6679 ┆ 0     ┆ F     ┆ 0    ┆ N74.8 ┆ 4     │
└──────┴──────┴───────┴───────┴──────┴───────┴───────┘

--- Détail des 10 exemples (code principal, libellé, code associé) ---

  Code principal : L62 (SID=5236, daget=F, plus=0)
  LID 5175 : maladies des ongles au cours de maladies classées ailleurs
  Code associé   : SID=0 (SID=0)

  Code principal : G46.2 (SID=3070, daget=G, plus=0)
  LID 3489 : syndrome de l'artère cérébrale postérieure
  Code associé   : I66.2 (SID=4059)

  Code principal : E10.2 (SID=2057, daget=S, plus=0)
  LID 2476 : diabète sucré insulino-dépendant | avec complications rénales
  Code associé   : SID=0 (SID=0)

  Code principal : H94.0 (SID=3751, daget=F, plus=0)
  LID 4110 : névrite acoustique au cours de maladies infectieuses et parasitaires classées ai
  Code associé   : SID=0 (SID=0)

  Code principal : K77.8 (SID=4926, daget=F, plus=0)
  LID 2225 : atteintes hépatiques au cours d'autres maladies classées ailleurs
  Code associé   : SID=0 (SID=0)

  Code principal : G94 (SID=3271, daget=F, plus=0)
  LID 3690 : autres affections du cerveau au cours de maladies classées ailleurs
  Code associé   : SID=0 (SID=0)

  Code principal : M82.1 (SID=5909, daget=G, plus=0)
  LID 5848 : ostéoporose au cours de maladies endocriniennes
  Code associé   : E32 (SID=2192)

  Code principal : H03.8 (SID=3323, daget=F, plus=0)
  LID 3742 : atteinte de la paupière au cours d'autres maladies classées ailleurs
  Code associé   : SID=0 (SID=0)

  Code principal : B05.0 (SID=499, daget=T, plus=0)
  LID 499 : rougeole compliquée d'une encéphalite
  Code associé   : G05.1 (SID=2929)

  Code principal : N74.8 (SID=6380, daget=F, plus=0)
  LID 6679 : affections inflammatoires pelviennes de la femme, au cours d'autres maladies cla
  Code associé   : SID=0 (SID=0)